//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.02 at 12:37:18 PM CET 
//


package it.latraccia.entity.anasic.risposta;


/**
 * *******************************************************                   INIZIO DEFINIZIONE TIPI COMPOSTI                   *******************************************************
 * Java content class for Intestazione_Types complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/simonebrunox/Desktop/SIC/XSD/Anagraf/RispostaAnaSIC.xsd line 58)
 * <p>
 * <pre>
 * &lt;complexType name="Intestazione_Types">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InfoMittDest" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Applicazione" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface IntestazioneTypes {


    /**
     * Informazioni che identificano univocamente un mittente
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getInfoMittDest();

    /**
     * Informazioni che identificano univocamente un mittente
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setInfoMittDest(java.lang.String value);

    /**
     * Dati che identificano univocamente un'applicazione che utilizza il WS
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getApplicazione();

    /**
     * Dati che identificano univocamente un'applicazione che utilizza il WS
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setApplicazione(java.lang.String value);

}
