//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.28 at 01:25:27 PM CET 
//


package it.latraccia.entity.anasic.richiesta.impl;

public class ModificaSedeTypesImpl implements it.latraccia.entity.anasic.richiesta.ModificaSedeTypes, com.sun.xml.bind.JAXBObject, it.latraccia.entity.anasic.richiesta.impl.runtime.UnmarshallableObject, it.latraccia.entity.anasic.richiesta.impl.runtime.XMLSerializable, it.latraccia.entity.anasic.richiesta.impl.runtime.ValidatableObject
{

    protected java.lang.String _IdAnagrafica;
    protected java.lang.String _CAP;
    protected java.lang.String _IdSede;
    protected java.lang.String _Bollo;
    protected java.lang.String _Indirizzo;
    protected java.lang.String _Telefono;
    protected java.lang.String _CodiceFiscaleOperatore;
    protected java.lang.String _NomeSede;
    protected java.lang.String _EMail;
    protected java.lang.String _Fax;
    protected java.lang.String _Comune;
    protected java.lang.String _TipoPagamento;
    public final static java.lang.Class version = (it.latraccia.entity.anasic.richiesta.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (it.latraccia.entity.anasic.richiesta.ModificaSedeTypes.class);
    }

    public java.lang.String getIdAnagrafica() {
        return _IdAnagrafica;
    }

    public void setIdAnagrafica(java.lang.String value) {
        _IdAnagrafica = value;
    }

    public java.lang.String getCAP() {
        return _CAP;
    }

    public void setCAP(java.lang.String value) {
        _CAP = value;
    }

    public java.lang.String getIdSede() {
        return _IdSede;
    }

    public void setIdSede(java.lang.String value) {
        _IdSede = value;
    }

    public java.lang.String getBollo() {
        return _Bollo;
    }

    public void setBollo(java.lang.String value) {
        _Bollo = value;
    }

    public java.lang.String getIndirizzo() {
        return _Indirizzo;
    }

    public void setIndirizzo(java.lang.String value) {
        _Indirizzo = value;
    }

    public java.lang.String getTelefono() {
        return _Telefono;
    }

    public void setTelefono(java.lang.String value) {
        _Telefono = value;
    }

    public java.lang.String getCodiceFiscaleOperatore() {
        return _CodiceFiscaleOperatore;
    }

    public void setCodiceFiscaleOperatore(java.lang.String value) {
        _CodiceFiscaleOperatore = value;
    }

    public java.lang.String getNomeSede() {
        return _NomeSede;
    }

    public void setNomeSede(java.lang.String value) {
        _NomeSede = value;
    }

    public java.lang.String getEMail() {
        return _EMail;
    }

    public void setEMail(java.lang.String value) {
        _EMail = value;
    }

    public java.lang.String getFax() {
        return _Fax;
    }

    public void setFax(java.lang.String value) {
        _Fax = value;
    }

    public java.lang.String getComune() {
        return _Comune;
    }

    public void setComune(java.lang.String value) {
        _Comune = value;
    }

    public java.lang.String getTipoPagamento() {
        return _TipoPagamento;
    }

    public void setTipoPagamento(java.lang.String value) {
        _TipoPagamento = value;
    }

    public it.latraccia.entity.anasic.richiesta.impl.runtime.UnmarshallingEventHandler createUnmarshaller(it.latraccia.entity.anasic.richiesta.impl.runtime.UnmarshallingContext context) {
        return new it.latraccia.entity.anasic.richiesta.impl.ModificaSedeTypesImpl.Unmarshaller(context);
    }

    public void serializeBody(it.latraccia.entity.anasic.richiesta.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("", "IdAnagrafica");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _IdAnagrafica), "IdAnagrafica");
        } catch (java.lang.Exception e) {
            it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "IdSede");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _IdSede), "IdSede");
        } catch (java.lang.Exception e) {
            it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "Indirizzo");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Indirizzo), "Indirizzo");
        } catch (java.lang.Exception e) {
            it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "Comune");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Comune), "Comune");
        } catch (java.lang.Exception e) {
            it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "CAP");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _CAP), "CAP");
        } catch (java.lang.Exception e) {
            it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        if (_Telefono!= null) {
            context.startElement("", "Telefono");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _Telefono), "Telefono");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_EMail!= null) {
            context.startElement("", "EMail");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _EMail), "EMail");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_Fax!= null) {
            context.startElement("", "Fax");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _Fax), "Fax");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_Bollo!= null) {
            context.startElement("", "Bollo");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _Bollo), "Bollo");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_NomeSede!= null) {
            context.startElement("", "NomeSede");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _NomeSede), "NomeSede");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_TipoPagamento!= null) {
            context.startElement("", "TipoPagamento");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _TipoPagamento), "TipoPagamento");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        context.startElement("", "CodiceFiscaleOperatore");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _CodiceFiscaleOperatore), "CodiceFiscaleOperatore");
        } catch (java.lang.Exception e) {
            it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
    }

    public void serializeAttributes(it.latraccia.entity.anasic.richiesta.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(it.latraccia.entity.anasic.richiesta.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (it.latraccia.entity.anasic.richiesta.ModificaSedeTypes.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000pp"
+"sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\'com.sun.msv.gram"
+"mar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/ms"
+"v/grammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003"
+"pp\u0000sq\u0000~\u0000\u0000ppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000"
+"\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom"
+"/sun/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000%com.sun.msv.datatype.xs"
+"d.PatternFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001[\u0000\bpatternst\u0000\u0013[Ljava/lang/String;xr"
+"\u0000;com.sun.msv.datatype.xsd.DataTypeWithLexicalConstraintFace"
+"tT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.DataTypeWithFacet\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012needValueCheckFlagL\u0000\bbaseTypet\u0000)L"
+"com/sun/msv/datatype/xsd/XSDatatypeImpl;L\u0000\fconcreteTypet\u0000\'Lc"
+"om/sun/msv/datatype/xsd/ConcreteType;L\u0000\tfacetNamet\u0000\u0012Ljava/la"
+"ng/String;xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq\u0000~\u0000\u001fL\u0000\btypeNameq\u0000~\u0000\u001fL\u0000\nwhiteSpacet\u0000.Lcom"
+"/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000\u0000psr\u00005com.sun."
+"msv.datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,"
+"com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0000\u0000s"
+"r\u0000#com.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlways"
+"Validxr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000 "
+"t\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0006stringq\u0000~\u0000&\u0001q\u0000~\u0000*t\u0000\u0007pa"
+"tternur\u0000\u0013[Ljava.lang.String;\u00ad\u00d2V\u00e7\u00e9\u001d{G\u0002\u0000\u0000xp\u0000\u0000\u0000\u0001t\u0000\t[0-9]{10}sr\u0000"
+"0com.sun.msv.grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000"
+"xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNa"
+"meq\u0000~\u0000\u001fL\u0000\fnamespaceURIq\u0000~\u0000\u001fxpt\u0000\u000estring-derivedq\u0000~\u0000#sr\u0000\u001dcom.s"
+"un.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000 com.sun.msv.g"
+"rammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\u0011xq"
+"\u0000~\u0000\u0003sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000\u0015ppsr\u0000\""
+"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000(q\u0000~\u0000+t\u0000\u0005Q"
+"Namesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collaps"
+"e\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000%q\u0000~\u00002sq\u0000~\u00003q\u0000~\u0000?q\u0000~\u0000+sr\u0000#com.sun.msv.gramm"
+"ar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001fL\u0000\fnamespaceUR"
+"Iq\u0000~\u0000\u001fxr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet"
+"\u0000)http://www.w3.org/2001/XMLSchema-instancesr\u00000com.sun.msv.g"
+"rammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000:\u0001q"
+"\u0000~\u0000Isq\u0000~\u0000Ct\u0000\fIdAnagraficaq\u0000~\u0000#sq\u0000~\u0000\u0010pp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0015ppsq\u0000~\u0000"
+"\u0019q\u0000~\u0000#pq\u0000~\u0000&\u0000\u0000q\u0000~\u0000*q\u0000~\u0000*q\u0000~\u0000-uq\u0000~\u0000.\u0000\u0000\u0000\u0001t\u0000\t[0-9]{10}q\u0000~\u00002sq\u0000~"
+"\u00003t\u0000\u000estring-derivedq\u0000~\u0000#sq\u0000~\u00006ppsq\u0000~\u00008q\u0000~\u0000;pq\u0000~\u0000<q\u0000~\u0000Eq\u0000~\u0000Is"
+"q\u0000~\u0000Ct\u0000\u0006IdSedeq\u0000~\u0000#sq\u0000~\u0000\u0010pp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0015ppq\u0000~\u0000*q\u0000~\u00002sq\u0000~\u00003"
+"q\u0000~\u0000,q\u0000~\u0000+sq\u0000~\u00006ppsq\u0000~\u00008q\u0000~\u0000;pq\u0000~\u0000<q\u0000~\u0000Eq\u0000~\u0000Isq\u0000~\u0000Ct\u0000\tIndiri"
+"zzoq\u0000~\u0000#sq\u0000~\u0000\u0010pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000[sq\u0000~\u00006ppsq\u0000~\u00008q\u0000~\u0000;pq\u0000~\u0000<q\u0000~\u0000E"
+"q\u0000~\u0000Isq\u0000~\u0000Ct\u0000\u0006Comuneq\u0000~\u0000#sq\u0000~\u0000\u0010pp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0015ppsr\u0000\'com.su"
+"n.msv.datatype.xsd.MaxLengthFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\tmaxLengthxr\u00009"
+"com.sun.msv.datatype.xsd.DataTypeWithValueConstraintFacet\"\u00a7R"
+"o\u00ca\u00c7\u008aT\u0002\u0000\u0000xq\u0000~\u0000\u001cq\u0000~\u0000#pq\u0000~\u0000&\u0000\u0001sr\u0000\'com.sun.msv.datatype.xsd.MinL"
+"engthFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\tminLengthxq\u0000~\u0000kq\u0000~\u0000#pq\u0000~\u0000&\u0000\u0000q\u0000~\u0000*q\u0000~"
+"\u0000*t\u0000\tminLength\u0000\u0000\u0000\u0001q\u0000~\u0000*t\u0000\tmaxLength\u0000\u0000\u0000\nq\u0000~\u00002sq\u0000~\u00003t\u0000\u000estring-"
+"derivedq\u0000~\u0000#sq\u0000~\u00006ppsq\u0000~\u00008q\u0000~\u0000;pq\u0000~\u0000<q\u0000~\u0000Eq\u0000~\u0000Isq\u0000~\u0000Ct\u0000\u0003CAPq"
+"\u0000~\u0000#sq\u0000~\u00006ppsq\u0000~\u0000\u0010q\u0000~\u0000;p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000[sq\u0000~\u00006ppsq\u0000~\u00008q\u0000~\u0000;pq\u0000"
+"~\u0000<q\u0000~\u0000Eq\u0000~\u0000Isq\u0000~\u0000Ct\u0000\bTelefonoq\u0000~\u0000#q\u0000~\u0000Isq\u0000~\u00006ppsq\u0000~\u0000\u0010q\u0000~\u0000;p"
+"\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000[sq\u0000~\u00006ppsq\u0000~\u00008q\u0000~\u0000;pq\u0000~\u0000<q\u0000~\u0000Eq\u0000~\u0000Isq\u0000~\u0000Ct\u0000\u0005EM"
+"ailq\u0000~\u0000#q\u0000~\u0000Isq\u0000~\u00006ppsq\u0000~\u0000\u0010q\u0000~\u0000;p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000[sq\u0000~\u00006ppsq\u0000~\u0000"
+"8q\u0000~\u0000;pq\u0000~\u0000<q\u0000~\u0000Eq\u0000~\u0000Isq\u0000~\u0000Ct\u0000\u0003Faxq\u0000~\u0000#q\u0000~\u0000Isq\u0000~\u00006ppsq\u0000~\u0000\u0010q\u0000"
+"~\u0000;p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0015ppsr\u0000)com.sun.msv.datatype.xsd.Enumeratio"
+"nFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0006valuest\u0000\u000fLjava/util/Set;xq\u0000~\u0000kq\u0000~\u0000#pq\u0000~\u0000"
+"&\u0000\u0000q\u0000~\u0000*q\u0000~\u0000*t\u0000\u000benumerationsr\u0000\u0011java.util.HashSet\u00baD\u0085\u0095\u0096\u00b8\u00b74\u0003\u0000\u0000x"
+"pw\f\u0000\u0000\u0000\u0010?@\u0000\u0000\u0000\u0000\u0000\u0002t\u0000\u0001St\u0000\u0001Nxq\u0000~\u00002sq\u0000~\u00003t\u0000\u000estring-derivedq\u0000~\u0000#sq\u0000"
+"~\u00006ppsq\u0000~\u00008q\u0000~\u0000;pq\u0000~\u0000<q\u0000~\u0000Eq\u0000~\u0000Isq\u0000~\u0000Ct\u0000\u0005Bolloq\u0000~\u0000#q\u0000~\u0000Isq\u0000~"
+"\u00006ppsq\u0000~\u0000\u0010q\u0000~\u0000;p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0015ppsq\u0000~\u0000jq\u0000~\u0000#pq\u0000~\u0000&\u0000\u0001sq\u0000~\u0000mq\u0000"
+"~\u0000#pq\u0000~\u0000&\u0000\u0000q\u0000~\u0000*q\u0000~\u0000*q\u0000~\u0000o\u0000\u0000\u0000\u0001q\u0000~\u0000*q\u0000~\u0000p\u0000\u0000\u0000\u000fq\u0000~\u00002sq\u0000~\u00003t\u0000\u000est"
+"ring-derivedq\u0000~\u0000#sq\u0000~\u00006ppsq\u0000~\u00008q\u0000~\u0000;pq\u0000~\u0000<q\u0000~\u0000Eq\u0000~\u0000Isq\u0000~\u0000Ct\u0000"
+"\bNomeSedeq\u0000~\u0000#q\u0000~\u0000Isq\u0000~\u00006ppsq\u0000~\u0000\u0010q\u0000~\u0000;p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000[sq\u0000~\u00006p"
+"psq\u0000~\u00008q\u0000~\u0000;pq\u0000~\u0000<q\u0000~\u0000Eq\u0000~\u0000Isq\u0000~\u0000Ct\u0000\rTipoPagamentoq\u0000~\u0000#q\u0000~\u0000I"
+"sq\u0000~\u0000\u0010pp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0015ppsq\u0000~\u0000\u0019q\u0000~\u0000#pq\u0000~\u0000&\u0000\u0001sq\u0000~\u0000jq\u0000~\u0000#pq\u0000~\u0000"
+"&\u0000\u0001sq\u0000~\u0000mq\u0000~\u0000#pq\u0000~\u0000&\u0000\u0000q\u0000~\u0000*q\u0000~\u0000*q\u0000~\u0000o\u0000\u0000\u0000\u0010q\u0000~\u0000*q\u0000~\u0000p\u0000\u0000\u0000\u0010q\u0000~\u0000*"
+"q\u0000~\u0000-uq\u0000~\u0000.\u0000\u0000\u0000\u0001t\u0000\u0011([a-zA-Z0-9]){16}q\u0000~\u00002sq\u0000~\u00003t\u0000\u000estring-deri"
+"vedq\u0000~\u0000#sq\u0000~\u00006ppsq\u0000~\u00008q\u0000~\u0000;pq\u0000~\u0000<q\u0000~\u0000Eq\u0000~\u0000Isq\u0000~\u0000Ct\u0000\u0016CodiceFi"
+"scaleOperatoreq\u0000~\u0000#sr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionPool$Cl"
+"osedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$ClosedHash"
+"\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/"
+"grammar/ExpressionPool;xp\u0000\u0000\u0000)\u0001pq\u0000~\u0000\tq\u0000~\u0000\nq\u0000~\u0000\u000eq\u0000~\u0000\fq\u0000~\u0000\u0014q\u0000~\u0000"
+"\u0007q\u0000~\u0000\u000bq\u0000~\u0000\u009eq\u0000~\u00007q\u0000~\u0000Uq\u0000~\u0000]q\u0000~\u0000cq\u0000~\u0000\rq\u0000~\u0000sq\u0000~\u0000\u000fq\u0000~\u0000zq\u0000~\u0000\u0081q\u0000~\u0000"
+"\u0088q\u0000~\u0000\u009aq\u0000~\u0000\u00a6q\u0000~\u0000\u00adq\u0000~\u0000\u00bbq\u0000~\u0000\bq\u0000~\u0000\u00a0q\u0000~\u0000\u008eq\u0000~\u0000\u0005q\u0000~\u0000Nq\u0000~\u0000wq\u0000~\u0000~q\u0000~\u0000"
+"\u0085q\u0000~\u0000\u00aaq\u0000~\u0000\u00b2q\u0000~\u0000\u0006q\u0000~\u0000hq\u0000~\u0000\u008cq\u0000~\u0000Zq\u0000~\u0000bq\u0000~\u0000yq\u0000~\u0000\u0080q\u0000~\u0000\u0087q\u0000~\u0000\u00acx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends it.latraccia.entity.anasic.richiesta.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(it.latraccia.entity.anasic.richiesta.impl.runtime.UnmarshallingContext context) {
            super(context, "-------------------------------------");
        }

        protected Unmarshaller(it.latraccia.entity.anasic.richiesta.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return it.latraccia.entity.anasic.richiesta.impl.ModificaSedeTypesImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  33 :
                        if (("CodiceFiscaleOperatore" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 34;
                            return ;
                        }
                        break;
                    case  12 :
                        if (("CAP" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 13;
                            return ;
                        }
                        break;
                    case  30 :
                        if (("TipoPagamento" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 31;
                            return ;
                        }
                        state = 33;
                        continue outer;
                    case  27 :
                        if (("NomeSede" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 28;
                            return ;
                        }
                        state = 30;
                        continue outer;
                    case  18 :
                        if (("EMail" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 19;
                            return ;
                        }
                        state = 21;
                        continue outer;
                    case  9 :
                        if (("Comune" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 10;
                            return ;
                        }
                        break;
                    case  0 :
                        if (("IdAnagrafica" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 1;
                            return ;
                        }
                        break;
                    case  3 :
                        if (("IdSede" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 4;
                            return ;
                        }
                        break;
                    case  24 :
                        if (("Bollo" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 25;
                            return ;
                        }
                        state = 27;
                        continue outer;
                    case  21 :
                        if (("Fax" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 22;
                            return ;
                        }
                        state = 24;
                        continue outer;
                    case  36 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  6 :
                        if (("Indirizzo" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 7;
                            return ;
                        }
                        break;
                    case  15 :
                        if (("Telefono" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 16;
                            return ;
                        }
                        state = 18;
                        continue outer;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  2 :
                        if (("IdAnagrafica" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  26 :
                        if (("Bollo" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 27;
                            return ;
                        }
                        break;
                    case  20 :
                        if (("EMail" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 21;
                            return ;
                        }
                        break;
                    case  30 :
                        state = 33;
                        continue outer;
                    case  27 :
                        state = 30;
                        continue outer;
                    case  5 :
                        if (("IdSede" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                    case  32 :
                        if (("TipoPagamento" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 33;
                            return ;
                        }
                        break;
                    case  14 :
                        if (("CAP" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 15;
                            return ;
                        }
                        break;
                    case  18 :
                        state = 21;
                        continue outer;
                    case  35 :
                        if (("CodiceFiscaleOperatore" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 36;
                            return ;
                        }
                        break;
                    case  17 :
                        if (("Telefono" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 18;
                            return ;
                        }
                        break;
                    case  8 :
                        if (("Indirizzo" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                    case  11 :
                        if (("Comune" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 12;
                            return ;
                        }
                        break;
                    case  24 :
                        state = 27;
                        continue outer;
                    case  21 :
                        state = 24;
                        continue outer;
                    case  36 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  23 :
                        if (("Fax" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 24;
                            return ;
                        }
                        break;
                    case  29 :
                        if (("NomeSede" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 30;
                            return ;
                        }
                        break;
                    case  15 :
                        state = 18;
                        continue outer;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  30 :
                        state = 33;
                        continue outer;
                    case  27 :
                        state = 30;
                        continue outer;
                    case  18 :
                        state = 21;
                        continue outer;
                    case  24 :
                        state = 27;
                        continue outer;
                    case  21 :
                        state = 24;
                        continue outer;
                    case  36 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  15 :
                        state = 18;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  30 :
                        state = 33;
                        continue outer;
                    case  27 :
                        state = 30;
                        continue outer;
                    case  18 :
                        state = 21;
                        continue outer;
                    case  24 :
                        state = 27;
                        continue outer;
                    case  21 :
                        state = 24;
                        continue outer;
                    case  36 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  15 :
                        state = 18;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  31 :
                            state = 32;
                            eatText1(value);
                            return ;
                        case  10 :
                            state = 11;
                            eatText2(value);
                            return ;
                        case  30 :
                            state = 33;
                            continue outer;
                        case  4 :
                            state = 5;
                            eatText3(value);
                            return ;
                        case  27 :
                            state = 30;
                            continue outer;
                        case  34 :
                            state = 35;
                            eatText4(value);
                            return ;
                        case  13 :
                            state = 14;
                            eatText5(value);
                            return ;
                        case  18 :
                            state = 21;
                            continue outer;
                        case  7 :
                            state = 8;
                            eatText6(value);
                            return ;
                        case  28 :
                            state = 29;
                            eatText7(value);
                            return ;
                        case  22 :
                            state = 23;
                            eatText8(value);
                            return ;
                        case  24 :
                            state = 27;
                            continue outer;
                        case  21 :
                            state = 24;
                            continue outer;
                        case  25 :
                            state = 26;
                            eatText9(value);
                            return ;
                        case  36 :
                            revertToParentFromText(value);
                            return ;
                        case  15 :
                            state = 18;
                            continue outer;
                        case  19 :
                            state = 20;
                            eatText10(value);
                            return ;
                        case  16 :
                            state = 17;
                            eatText11(value);
                            return ;
                        case  1 :
                            state = 2;
                            eatText12(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _TipoPagamento = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Comune = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _IdSede = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _CodiceFiscaleOperatore = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText5(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _CAP = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText6(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Indirizzo = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText7(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _NomeSede = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText8(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Fax = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText9(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Bollo = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText10(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _EMail = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText11(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Telefono = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText12(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _IdAnagrafica = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
