//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.02 at 12:37:18 PM CET 
//


package it.latraccia.entity.anasic.risposta;


/**
 * Java content class for Risposta_ModificaContoBancario_Types complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/simonebrunox/Desktop/SIC/XSD/Anagraf/RispostaAnaSIC.xsd line 967)
 * <p>
 * <pre>
 * &lt;complexType name="Risposta_ModificaContoBancario_Types">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdAnagrafica">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-9]{10}"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="IdSede">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-9]{10}"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="IdContoCorrente">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-9]{10}"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface RispostaModificaContoBancarioTypes {


    /**
     * Identificativo Anagrafica SIC a cui la sede appartiene
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIdAnagrafica();

    /**
     * Identificativo Anagrafica SIC a cui la sede appartiene
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIdAnagrafica(java.lang.String value);

    /**
     * Identificativo Sede SIC
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIdSede();

    /**
     * Identificativo Sede SIC
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIdSede(java.lang.String value);

    /**
     * Identificativo del Conto Corrente
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIdContoCorrente();

    /**
     * Identificativo del Conto Corrente
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIdContoCorrente(java.lang.String value);

}
