//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.27 at 01:25:11 AM CEST 
//


package it.latraccia.entity.sic.richiesta;


/**
 * Java content class for Allegato_Types complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/simonebrunox/Desktop/SIC/RichiestaSIC.xsd line 801)
 * <p>
 * <pre>
 * &lt;complexType name="Allegato_Types">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodiceProgetto">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-9999999999]"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="Causale">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-9999999999]"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="Importo" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="CodiceFiscaleBeneficiario">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="([a-zA-Z0-9]){16}"/>
 *             &lt;minLength value="16"/>
 *             &lt;maxLength value="16"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface AllegatoTypes {


    /**
     * Codice causale
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCausale();

    /**
     * Codice causale
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCausale(java.lang.String value);

    /**
     * Codice del progetto
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCodiceProgetto();

    /**
     * Codice del progetto
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCodiceProgetto(java.lang.String value);

    /**
     * Codice Fiscale del beneficiario
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCodiceFiscaleBeneficiario();

    /**
     * Codice Fiscale del beneficiario
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCodiceFiscaleBeneficiario(java.lang.String value);

    /**
     * Importo
     * 
     */
    double getImporto();

    /**
     * Importo
     * 
     */
    void setImporto(double value);

}
