//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.27 at 01:25:11 AM CEST 
//


package it.latraccia.entity.sic.richiesta;


/**
 * Java content class for InterrogaMandatiBeneficiariAtto_Types complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/simonebrunox/Desktop/SIC/RichiestaSIC.xsd line 1096)
 * <p>
 * <pre>
 * &lt;complexType name="InterrogaMandatiBeneficiariAtto_Types">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TipoAtto">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="15"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="NumeroAtto" minOccurs="0">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-99999999999999999999]"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="DataAtto" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Ufficio">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="10"/>
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="NumeroLiquidazione" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface InterrogaMandatiBeneficiariAttoTypes {


    /**
     * Numero della liquidazione del mandato
     * 
     */
    long getNumeroLiquidazione();

    /**
     * Numero della liquidazione del mandato
     * 
     */
    void setNumeroLiquidazione(long value);

    /**
     * Tipo dell'atto
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getTipoAtto();

    /**
     * Tipo dell'atto
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setTipoAtto(java.lang.String value);

    /**
     * Numero dell'atto
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getNumeroAtto();

    /**
     * Numero dell'atto
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setNumeroAtto(java.lang.String value);

    /**
     * Ufficio di riferimento
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getUfficio();

    /**
     * Ufficio di riferimento
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setUfficio(java.lang.String value);

    /**
     * Data dell'atto
     * 
     * @return
     *     possible object is
     *     {@link java.util.Calendar}
     */
    java.util.Calendar getDataAtto();

    /**
     * Data dell'atto
     * 
     * @param value
     *     allowed object is
     *     {@link java.util.Calendar}
     */
    void setDataAtto(java.util.Calendar value);

}
