//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.27 at 01:25:11 AM CEST 
//


package it.latraccia.entity.sic.richiesta;


/**
 * Java content class for Richiesta_Types complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/simonebrunox/Desktop/SIC/RichiestaSIC.xsd line 38)
 * <p>
 * <pre>
 * &lt;complexType name="Richiesta_Types">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="InterrogazioneCapitoli" type="{}InterrogazioneCapitoli_Types"/>
 *         &lt;element name="InterrogazioneCapitoliLiquidazioni" type="{}InterrogazioneCapitoli_Types"/>
 *         &lt;element name="InterrogazioneBilancio" type="{}InterrogazioneBilancio_Types"/>
 *         &lt;element name="InterrogazioneObiettiviGestionali" type="{}InterrogazioneObiettiviGestionali_Types"/>
 *         &lt;element name="DisponibilitaPreImpegno" type="{}DisponibilitaPreImpegno_Types"/>
 *         &lt;element name="InterrogazioneImpegniAperti" type="{}InterrogazioneImpegniAperti_Types"/>
 *         &lt;element name="InterrogazioneLiquidazioniAperte" type="{}InterrogazioneLiquidazioniAperte_Types"/>
 *         &lt;element name="InterrogazionePreimpegniAperti" type="{}InterrogazionePreimpegniAperti_Types"/>
 *         &lt;element name="InterrogazioneImpegniPerenti" type="{}InterrogazioneImpegniPerenti_Types"/>
 *         &lt;element name="PrenotazionePreimpegni" type="{}PrenotazionePreimpegni_Types"/>
 *         &lt;element name="CreateDelDocumento" type="{}CreateDelDocumento_Types"/>
 *         &lt;element name="DisponibilitaImpegno" type="{}DisponibilitaImpegno_Types"/>
 *         &lt;element name="InterrogazioneTipologiaReddito" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="InterrogaCodiceSiope" type="{}InterrogaCodiceSiope_Types"/>
 *         &lt;element name="InterrogaCapitoloEntrate" type="{}InterrogaCapitoloEntrata_Types"/>
 *         &lt;element name="InterrogaReversaliCollegabili" type="{}InterrogaReversaliCollegabili_Types"/>
 *         &lt;element name="InterrogaBeneficiariLiq" type="{}InterrogaBeneficiariLiq_Types"/>
 *         &lt;element name="InterrogaMandatiBeneficiariAtto" type="{}InterrogaMandatiBeneficiariAtto_Types"/>
 *         &lt;element name="InterrogazionePCF" type="{}InterrogazionePCF_Types"/>
 *         &lt;element name="InterrogazioneMandatiTrasparenza" type="{}InterrogazioneMandatiTrasparenza_Types"/>
 *         &lt;element name="InterrogazioneContratti" type="{}InterrogazioneContratti_Types"/>
 *         &lt;element name="InterrogazioneListaContratti" type="{}InterrogazioneListaContratti_Types"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface RichiestaTypes {


    /**
     * Servizio di interrogazione degli obiettivi gestionali
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneObiettiviGestionaliTypes}
     */
    it.latraccia.entity.sic.richiesta.InterrogazioneObiettiviGestionaliTypes getInterrogazioneObiettiviGestionali();

    /**
     * Servizio di interrogazione degli obiettivi gestionali
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneObiettiviGestionaliTypes}
     */
    void setInterrogazioneObiettiviGestionali(it.latraccia.entity.sic.richiesta.InterrogazioneObiettiviGestionaliTypes value);

    /**
     * Servizio di interrogazione delle liquidazioni aperte ossia con residuo maggiore di 0
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneLiquidazioniAperteTypes}
     */
    it.latraccia.entity.sic.richiesta.InterrogazioneLiquidazioniAperteTypes getInterrogazioneLiquidazioniAperte();

    /**
     * Servizio di interrogazione delle liquidazioni aperte ossia con residuo maggiore di 0
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneLiquidazioniAperteTypes}
     */
    void setInterrogazioneLiquidazioniAperte(it.latraccia.entity.sic.richiesta.InterrogazioneLiquidazioniAperteTypes value);

    /**
     * Servizio per la richiesta dei Mandati per Trasparenza
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneMandatiTrasparenzaTypes}
     */
    it.latraccia.entity.sic.richiesta.InterrogazioneMandatiTrasparenzaTypes getInterrogazioneMandatiTrasparenza();

    /**
     * Servizio per la richiesta dei Mandati per Trasparenza
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneMandatiTrasparenzaTypes}
     */
    void setInterrogazioneMandatiTrasparenza(it.latraccia.entity.sic.richiesta.InterrogazioneMandatiTrasparenzaTypes value);

    /**
     * Servizio di interrogazione degli impegni in perenzione
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneImpegniPerentiTypes}
     */
    it.latraccia.entity.sic.richiesta.InterrogazioneImpegniPerentiTypes getInterrogazioneImpegniPerenti();

    /**
     * Servizio di interrogazione degli impegni in perenzione
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneImpegniPerentiTypes}
     */
    void setInterrogazioneImpegniPerenti(it.latraccia.entity.sic.richiesta.InterrogazioneImpegniPerentiTypes value);

    /**
     * Servizio di prenotazione dei pre-impegni
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.PrenotazionePreimpegniTypes}
     */
    it.latraccia.entity.sic.richiesta.PrenotazionePreimpegniTypes getPrenotazionePreimpegni();

    /**
     * Servizio di prenotazione dei pre-impegni
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.PrenotazionePreimpegniTypes}
     */
    void setPrenotazionePreimpegni(it.latraccia.entity.sic.richiesta.PrenotazionePreimpegniTypes value);

    /**
     * Servizio per la richiesta dei Piani Contabili Finanziari
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazionePCFTypes}
     */
    it.latraccia.entity.sic.richiesta.InterrogazionePCFTypes getInterrogazionePCF();

    /**
     * Servizio per la richiesta dei Piani Contabili Finanziari
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazionePCFTypes}
     */
    void setInterrogazionePCF(it.latraccia.entity.sic.richiesta.InterrogazionePCFTypes value);

    /**
     * Servizio per la richiesta dell'elenco delle reversali collegabili
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogaBeneficiariLiqTypes}
     */
    it.latraccia.entity.sic.richiesta.InterrogaBeneficiariLiqTypes getInterrogaBeneficiariLiq();

    /**
     * Servizio per la richiesta dell'elenco delle reversali collegabili
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogaBeneficiariLiqTypes}
     */
    void setInterrogaBeneficiariLiq(it.latraccia.entity.sic.richiesta.InterrogaBeneficiariLiqTypes value);

    /**
     * Servizio per la generazione o cancellazione di un documento generico (impegno, liquidazione, disimpegno, ...)
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.CreateDelDocumentoTypes}
     */
    it.latraccia.entity.sic.richiesta.CreateDelDocumentoTypes getCreateDelDocumento();

    /**
     * Servizio per la generazione o cancellazione di un documento generico (impegno, liquidazione, disimpegno, ...)
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.CreateDelDocumentoTypes}
     */
    void setCreateDelDocumento(it.latraccia.entity.sic.richiesta.CreateDelDocumentoTypes value);

    /**
     * Servizio per la richiesta dell'elenco dei Mandati con i rispettivi Beneficiari riferiti ad un determinato Atto
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogaMandatiBeneficiariAttoTypes}
     */
    it.latraccia.entity.sic.richiesta.InterrogaMandatiBeneficiariAttoTypes getInterrogaMandatiBeneficiariAtto();

    /**
     * Servizio per la richiesta dell'elenco dei Mandati con i rispettivi Beneficiari riferiti ad un determinato Atto
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogaMandatiBeneficiariAttoTypes}
     */
    void setInterrogaMandatiBeneficiariAtto(it.latraccia.entity.sic.richiesta.InterrogaMandatiBeneficiariAttoTypes value);

    /**
     * Servizio per la richiesta dei Contratti
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneContrattiTypes}
     */
    it.latraccia.entity.sic.richiesta.InterrogazioneContrattiTypes getInterrogazioneContratti();

    /**
     * Servizio per la richiesta dei Contratti
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneContrattiTypes}
     */
    void setInterrogazioneContratti(it.latraccia.entity.sic.richiesta.InterrogazioneContrattiTypes value);

    /**
     * Servizio di interrogazione capitoli associati alle liquidazioni
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneCapitoliTypes}
     */
    it.latraccia.entity.sic.richiesta.InterrogazioneCapitoliTypes getInterrogazioneCapitoliLiquidazioni();

    /**
     * Servizio di interrogazione capitoli associati alle liquidazioni
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneCapitoliTypes}
     */
    void setInterrogazioneCapitoliLiquidazioni(it.latraccia.entity.sic.richiesta.InterrogazioneCapitoliTypes value);

    /**
     * Servizio per la richiesta dei codici SIOPE
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogaCodiceSiopeTypes}
     */
    it.latraccia.entity.sic.richiesta.InterrogaCodiceSiopeTypes getInterrogaCodiceSiope();

    /**
     * Servizio per la richiesta dei codici SIOPE
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogaCodiceSiopeTypes}
     */
    void setInterrogaCodiceSiope(it.latraccia.entity.sic.richiesta.InterrogaCodiceSiopeTypes value);

    /**
     * Servizio di interrogazione capitolo
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneCapitoliTypes}
     */
    it.latraccia.entity.sic.richiesta.InterrogazioneCapitoliTypes getInterrogazioneCapitoli();

    /**
     * Servizio di interrogazione capitolo
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneCapitoliTypes}
     */
    void setInterrogazioneCapitoli(it.latraccia.entity.sic.richiesta.InterrogazioneCapitoliTypes value);

    /**
     * Servizio per la richiesta della disponibilità residua su PreImpegno
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.DisponibilitaPreImpegnoTypes}
     */
    it.latraccia.entity.sic.richiesta.DisponibilitaPreImpegnoTypes getDisponibilitaPreImpegno();

    /**
     * Servizio per la richiesta della disponibilità residua su PreImpegno
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.DisponibilitaPreImpegnoTypes}
     */
    void setDisponibilitaPreImpegno(it.latraccia.entity.sic.richiesta.DisponibilitaPreImpegnoTypes value);

    /**
     * Servizio di interrogazione della tipologia reddito
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.AnyType}
     */
    it.latraccia.entity.sic.richiesta.AnyType getInterrogazioneTipologiaReddito();

    /**
     * Servizio di interrogazione della tipologia reddito
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.AnyType}
     */
    void setInterrogazioneTipologiaReddito(it.latraccia.entity.sic.richiesta.AnyType value);

    /**
     * Servizio per la richiesta dell'elenco delle reversali collegabili
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogaReversaliCollegabiliTypes}
     */
    it.latraccia.entity.sic.richiesta.InterrogaReversaliCollegabiliTypes getInterrogaReversaliCollegabili();

    /**
     * Servizio per la richiesta dell'elenco delle reversali collegabili
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogaReversaliCollegabiliTypes}
     */
    void setInterrogaReversaliCollegabili(it.latraccia.entity.sic.richiesta.InterrogaReversaliCollegabiliTypes value);

    /**
     * Servizio di interrogazione degli impegni aperti
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneImpegniApertiTypes}
     */
    it.latraccia.entity.sic.richiesta.InterrogazioneImpegniApertiTypes getInterrogazioneImpegniAperti();

    /**
     * Servizio di interrogazione degli impegni aperti
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneImpegniApertiTypes}
     */
    void setInterrogazioneImpegniAperti(it.latraccia.entity.sic.richiesta.InterrogazioneImpegniApertiTypes value);

    /**
     * Servizio di interrogazione bilancio
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneBilancioTypes}
     */
    it.latraccia.entity.sic.richiesta.InterrogazioneBilancioTypes getInterrogazioneBilancio();

    /**
     * Servizio di interrogazione bilancio
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneBilancioTypes}
     */
    void setInterrogazioneBilancio(it.latraccia.entity.sic.richiesta.InterrogazioneBilancioTypes value);

    /**
     * Servizio per la richiesta di una Lista di Contratti
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneListaContrattiTypes}
     */
    it.latraccia.entity.sic.richiesta.InterrogazioneListaContrattiTypes getInterrogazioneListaContratti();

    /**
     * Servizio per la richiesta di una Lista di Contratti
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazioneListaContrattiTypes}
     */
    void setInterrogazioneListaContratti(it.latraccia.entity.sic.richiesta.InterrogazioneListaContrattiTypes value);

    /**
     * Servizio per la richiesta della disponibilità residua su Impegno
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.DisponibilitaImpegnoTypes}
     */
    it.latraccia.entity.sic.richiesta.DisponibilitaImpegnoTypes getDisponibilitaImpegno();

    /**
     * Servizio per la richiesta della disponibilità residua su Impegno
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.DisponibilitaImpegnoTypes}
     */
    void setDisponibilitaImpegno(it.latraccia.entity.sic.richiesta.DisponibilitaImpegnoTypes value);

    /**
     * Servizio di interrogazione dei pre-impegni aperti
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazionePreimpegniApertiTypes}
     */
    it.latraccia.entity.sic.richiesta.InterrogazionePreimpegniApertiTypes getInterrogazionePreimpegniAperti();

    /**
     * Servizio di interrogazione dei pre-impegni aperti
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogazionePreimpegniApertiTypes}
     */
    void setInterrogazionePreimpegniAperti(it.latraccia.entity.sic.richiesta.InterrogazionePreimpegniApertiTypes value);

    /**
     * Servizio per la richiesta dei codici SIOPE
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogaCapitoloEntrataTypes}
     */
    it.latraccia.entity.sic.richiesta.InterrogaCapitoloEntrataTypes getInterrogaCapitoloEntrate();

    /**
     * Servizio per la richiesta dei codici SIOPE
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.richiesta.InterrogaCapitoloEntrataTypes}
     */
    void setInterrogaCapitoloEntrate(it.latraccia.entity.sic.richiesta.InterrogaCapitoloEntrataTypes value);

}
