//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.28 at 01:25:27 PM CET 
//


package it.latraccia.entity.anasic.richiesta.impl;

public class RichiestaTypesImpl implements it.latraccia.entity.anasic.richiesta.RichiestaTypes, com.sun.xml.bind.JAXBObject, it.latraccia.entity.anasic.richiesta.impl.runtime.UnmarshallableObject, it.latraccia.entity.anasic.richiesta.impl.runtime.XMLSerializable, it.latraccia.entity.anasic.richiesta.impl.runtime.ValidatableObject
{

    protected it.latraccia.entity.anasic.richiesta.CreaContoBancarioTypes _CreaContoBancario;
    protected it.latraccia.entity.anasic.richiesta.ModificaContoBancarioTypes _ModificaContoBancario;
    protected it.latraccia.entity.anasic.richiesta.InterrogaAnagraficaTypes _InterrogaAnagrafica;
    protected it.latraccia.entity.anasic.richiesta.CreaSedeTypes _CreaSede;
    protected it.latraccia.entity.anasic.richiesta.ModificaAnagraficaTypes _ModificaAnagrafica;
    protected it.latraccia.entity.anasic.richiesta.ModificaSedeTypes _ModificaSede;
    protected it.latraccia.entity.anasic.richiesta.InterrogaComuniTypes _InterrogaComuni;
    protected it.latraccia.entity.anasic.richiesta.VerificaAnagraficaTypes _VerificaAnagrafica;
    protected it.latraccia.entity.anasic.richiesta.CreaAnagraficaTypes _CreaAnagrafica;
    protected it.latraccia.entity.anasic.richiesta.CaricamentoAnagraficheTypes _CaricamentoAnagrafiche;
    protected it.latraccia.entity.anasic.richiesta.InterrogaAnagraficaContrattiTypes _InterrogaAnagraficaContratti;
    public final static java.lang.Class version = (it.latraccia.entity.anasic.richiesta.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (it.latraccia.entity.anasic.richiesta.RichiestaTypes.class);
    }

    public it.latraccia.entity.anasic.richiesta.CreaContoBancarioTypes getCreaContoBancario() {
        return _CreaContoBancario;
    }

    public void setCreaContoBancario(it.latraccia.entity.anasic.richiesta.CreaContoBancarioTypes value) {
        _CreaContoBancario = value;
    }

    public it.latraccia.entity.anasic.richiesta.ModificaContoBancarioTypes getModificaContoBancario() {
        return _ModificaContoBancario;
    }

    public void setModificaContoBancario(it.latraccia.entity.anasic.richiesta.ModificaContoBancarioTypes value) {
        _ModificaContoBancario = value;
    }

    public it.latraccia.entity.anasic.richiesta.InterrogaAnagraficaTypes getInterrogaAnagrafica() {
        return _InterrogaAnagrafica;
    }

    public void setInterrogaAnagrafica(it.latraccia.entity.anasic.richiesta.InterrogaAnagraficaTypes value) {
        _InterrogaAnagrafica = value;
    }

    public it.latraccia.entity.anasic.richiesta.CreaSedeTypes getCreaSede() {
        return _CreaSede;
    }

    public void setCreaSede(it.latraccia.entity.anasic.richiesta.CreaSedeTypes value) {
        _CreaSede = value;
    }

    public it.latraccia.entity.anasic.richiesta.ModificaAnagraficaTypes getModificaAnagrafica() {
        return _ModificaAnagrafica;
    }

    public void setModificaAnagrafica(it.latraccia.entity.anasic.richiesta.ModificaAnagraficaTypes value) {
        _ModificaAnagrafica = value;
    }

    public it.latraccia.entity.anasic.richiesta.ModificaSedeTypes getModificaSede() {
        return _ModificaSede;
    }

    public void setModificaSede(it.latraccia.entity.anasic.richiesta.ModificaSedeTypes value) {
        _ModificaSede = value;
    }

    public it.latraccia.entity.anasic.richiesta.InterrogaComuniTypes getInterrogaComuni() {
        return _InterrogaComuni;
    }

    public void setInterrogaComuni(it.latraccia.entity.anasic.richiesta.InterrogaComuniTypes value) {
        _InterrogaComuni = value;
    }

    public it.latraccia.entity.anasic.richiesta.VerificaAnagraficaTypes getVerificaAnagrafica() {
        return _VerificaAnagrafica;
    }

    public void setVerificaAnagrafica(it.latraccia.entity.anasic.richiesta.VerificaAnagraficaTypes value) {
        _VerificaAnagrafica = value;
    }

    public it.latraccia.entity.anasic.richiesta.CreaAnagraficaTypes getCreaAnagrafica() {
        return _CreaAnagrafica;
    }

    public void setCreaAnagrafica(it.latraccia.entity.anasic.richiesta.CreaAnagraficaTypes value) {
        _CreaAnagrafica = value;
    }

    public it.latraccia.entity.anasic.richiesta.CaricamentoAnagraficheTypes getCaricamentoAnagrafiche() {
        return _CaricamentoAnagrafiche;
    }

    public void setCaricamentoAnagrafiche(it.latraccia.entity.anasic.richiesta.CaricamentoAnagraficheTypes value) {
        _CaricamentoAnagrafiche = value;
    }

    public it.latraccia.entity.anasic.richiesta.InterrogaAnagraficaContrattiTypes getInterrogaAnagraficaContratti() {
        return _InterrogaAnagraficaContratti;
    }

    public void setInterrogaAnagraficaContratti(it.latraccia.entity.anasic.richiesta.InterrogaAnagraficaContrattiTypes value) {
        _InterrogaAnagraficaContratti = value;
    }

    public it.latraccia.entity.anasic.richiesta.impl.runtime.UnmarshallingEventHandler createUnmarshaller(it.latraccia.entity.anasic.richiesta.impl.runtime.UnmarshallingContext context) {
        return new it.latraccia.entity.anasic.richiesta.impl.RichiestaTypesImpl.Unmarshaller(context);
    }

    public void serializeBody(it.latraccia.entity.anasic.richiesta.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (((((((((((_VerificaAnagrafica == null)&&(_InterrogaComuni == null))&&(_ModificaSede == null))&&(_CreaSede == null))&&(_ModificaAnagrafica == null))&&(_ModificaContoBancario == null))&&(_CaricamentoAnagrafiche == null))&&(_CreaAnagrafica == null))&&(_InterrogaAnagrafica!= null))&&(_CreaContoBancario == null))&&(_InterrogaAnagraficaContratti == null)) {
            context.startElement("", "InterrogaAnagrafica");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _InterrogaAnagrafica), "InterrogaAnagrafica");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _InterrogaAnagrafica), "InterrogaAnagrafica");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _InterrogaAnagrafica), "InterrogaAnagrafica");
            context.endElement();
        } else {
            if (((((((((((_VerificaAnagrafica == null)&&(_InterrogaComuni == null))&&(_ModificaSede == null))&&(_CreaSede == null))&&(_ModificaAnagrafica == null))&&(_ModificaContoBancario == null))&&(_CaricamentoAnagrafiche == null))&&(_CreaAnagrafica == null))&&(_InterrogaAnagrafica == null))&&(_CreaContoBancario == null))&&(_InterrogaAnagraficaContratti!= null)) {
                context.startElement("", "InterrogaAnagraficaContratti");
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _InterrogaAnagraficaContratti), "InterrogaAnagraficaContratti");
                context.endNamespaceDecls();
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _InterrogaAnagraficaContratti), "InterrogaAnagraficaContratti");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _InterrogaAnagraficaContratti), "InterrogaAnagraficaContratti");
                context.endElement();
            } else {
                if (((((((((((_VerificaAnagrafica!= null)&&(_InterrogaComuni == null))&&(_ModificaSede == null))&&(_CreaSede == null))&&(_ModificaAnagrafica == null))&&(_ModificaContoBancario == null))&&(_CaricamentoAnagrafiche == null))&&(_CreaAnagrafica == null))&&(_InterrogaAnagrafica == null))&&(_CreaContoBancario == null))&&(_InterrogaAnagraficaContratti == null)) {
                    context.startElement("", "VerificaAnagrafica");
                    context.childAsURIs(((com.sun.xml.bind.JAXBObject) _VerificaAnagrafica), "VerificaAnagrafica");
                    context.endNamespaceDecls();
                    context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _VerificaAnagrafica), "VerificaAnagrafica");
                    context.endAttributes();
                    context.childAsBody(((com.sun.xml.bind.JAXBObject) _VerificaAnagrafica), "VerificaAnagrafica");
                    context.endElement();
                } else {
                    if (((((((((((_VerificaAnagrafica == null)&&(_InterrogaComuni == null))&&(_ModificaSede == null))&&(_CreaSede == null))&&(_ModificaAnagrafica == null))&&(_ModificaContoBancario == null))&&(_CaricamentoAnagrafiche == null))&&(_CreaAnagrafica!= null))&&(_InterrogaAnagrafica == null))&&(_CreaContoBancario == null))&&(_InterrogaAnagraficaContratti == null)) {
                        context.startElement("", "CreaAnagrafica");
                        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _CreaAnagrafica), "CreaAnagrafica");
                        context.endNamespaceDecls();
                        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _CreaAnagrafica), "CreaAnagrafica");
                        context.endAttributes();
                        context.childAsBody(((com.sun.xml.bind.JAXBObject) _CreaAnagrafica), "CreaAnagrafica");
                        context.endElement();
                    } else {
                        if (((((((((((_VerificaAnagrafica == null)&&(_InterrogaComuni == null))&&(_ModificaSede == null))&&(_CreaSede!= null))&&(_ModificaAnagrafica == null))&&(_ModificaContoBancario == null))&&(_CaricamentoAnagrafiche == null))&&(_CreaAnagrafica == null))&&(_InterrogaAnagrafica == null))&&(_CreaContoBancario == null))&&(_InterrogaAnagraficaContratti == null)) {
                            context.startElement("", "CreaSede");
                            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _CreaSede), "CreaSede");
                            context.endNamespaceDecls();
                            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _CreaSede), "CreaSede");
                            context.endAttributes();
                            context.childAsBody(((com.sun.xml.bind.JAXBObject) _CreaSede), "CreaSede");
                            context.endElement();
                        } else {
                            if (((((((((((_VerificaAnagrafica == null)&&(_InterrogaComuni == null))&&(_ModificaSede == null))&&(_CreaSede == null))&&(_ModificaAnagrafica == null))&&(_ModificaContoBancario == null))&&(_CaricamentoAnagrafiche == null))&&(_CreaAnagrafica == null))&&(_InterrogaAnagrafica == null))&&(_CreaContoBancario!= null))&&(_InterrogaAnagraficaContratti == null)) {
                                context.startElement("", "CreaContoBancario");
                                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _CreaContoBancario), "CreaContoBancario");
                                context.endNamespaceDecls();
                                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _CreaContoBancario), "CreaContoBancario");
                                context.endAttributes();
                                context.childAsBody(((com.sun.xml.bind.JAXBObject) _CreaContoBancario), "CreaContoBancario");
                                context.endElement();
                            } else {
                                if (((((((((((_VerificaAnagrafica == null)&&(_InterrogaComuni!= null))&&(_ModificaSede == null))&&(_CreaSede == null))&&(_ModificaAnagrafica == null))&&(_ModificaContoBancario == null))&&(_CaricamentoAnagrafiche == null))&&(_CreaAnagrafica == null))&&(_InterrogaAnagrafica == null))&&(_CreaContoBancario == null))&&(_InterrogaAnagraficaContratti == null)) {
                                    context.startElement("", "InterrogaComuni");
                                    context.childAsURIs(((com.sun.xml.bind.JAXBObject) _InterrogaComuni), "InterrogaComuni");
                                    context.endNamespaceDecls();
                                    context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _InterrogaComuni), "InterrogaComuni");
                                    context.endAttributes();
                                    context.childAsBody(((com.sun.xml.bind.JAXBObject) _InterrogaComuni), "InterrogaComuni");
                                    context.endElement();
                                } else {
                                    if (((((((((((_VerificaAnagrafica == null)&&(_InterrogaComuni == null))&&(_ModificaSede == null))&&(_CreaSede == null))&&(_ModificaAnagrafica!= null))&&(_ModificaContoBancario == null))&&(_CaricamentoAnagrafiche == null))&&(_CreaAnagrafica == null))&&(_InterrogaAnagrafica == null))&&(_CreaContoBancario == null))&&(_InterrogaAnagraficaContratti == null)) {
                                        context.startElement("", "ModificaAnagrafica");
                                        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _ModificaAnagrafica), "ModificaAnagrafica");
                                        context.endNamespaceDecls();
                                        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _ModificaAnagrafica), "ModificaAnagrafica");
                                        context.endAttributes();
                                        context.childAsBody(((com.sun.xml.bind.JAXBObject) _ModificaAnagrafica), "ModificaAnagrafica");
                                        context.endElement();
                                    } else {
                                        if (((((((((((_VerificaAnagrafica == null)&&(_InterrogaComuni == null))&&(_ModificaSede!= null))&&(_CreaSede == null))&&(_ModificaAnagrafica == null))&&(_ModificaContoBancario == null))&&(_CaricamentoAnagrafiche == null))&&(_CreaAnagrafica == null))&&(_InterrogaAnagrafica == null))&&(_CreaContoBancario == null))&&(_InterrogaAnagraficaContratti == null)) {
                                            context.startElement("", "ModificaSede");
                                            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _ModificaSede), "ModificaSede");
                                            context.endNamespaceDecls();
                                            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _ModificaSede), "ModificaSede");
                                            context.endAttributes();
                                            context.childAsBody(((com.sun.xml.bind.JAXBObject) _ModificaSede), "ModificaSede");
                                            context.endElement();
                                        } else {
                                            if (((((((((((_VerificaAnagrafica == null)&&(_InterrogaComuni == null))&&(_ModificaSede == null))&&(_CreaSede == null))&&(_ModificaAnagrafica == null))&&(_ModificaContoBancario!= null))&&(_CaricamentoAnagrafiche == null))&&(_CreaAnagrafica == null))&&(_InterrogaAnagrafica == null))&&(_CreaContoBancario == null))&&(_InterrogaAnagraficaContratti == null)) {
                                                context.startElement("", "ModificaContoBancario");
                                                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _ModificaContoBancario), "ModificaContoBancario");
                                                context.endNamespaceDecls();
                                                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _ModificaContoBancario), "ModificaContoBancario");
                                                context.endAttributes();
                                                context.childAsBody(((com.sun.xml.bind.JAXBObject) _ModificaContoBancario), "ModificaContoBancario");
                                                context.endElement();
                                            } else {
                                                if (((((((((((_VerificaAnagrafica == null)&&(_InterrogaComuni == null))&&(_ModificaSede == null))&&(_CreaSede == null))&&(_ModificaAnagrafica == null))&&(_ModificaContoBancario == null))&&(_CaricamentoAnagrafiche!= null))&&(_CreaAnagrafica == null))&&(_InterrogaAnagrafica == null))&&(_CreaContoBancario == null))&&(_InterrogaAnagraficaContratti == null)) {
                                                    context.startElement("", "CaricamentoAnagrafiche");
                                                    context.childAsURIs(((com.sun.xml.bind.JAXBObject) _CaricamentoAnagrafiche), "CaricamentoAnagrafiche");
                                                    context.endNamespaceDecls();
                                                    context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _CaricamentoAnagrafiche), "CaricamentoAnagrafiche");
                                                    context.endAttributes();
                                                    context.childAsBody(((com.sun.xml.bind.JAXBObject) _CaricamentoAnagrafiche), "CaricamentoAnagrafiche");
                                                    context.endElement();
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    public void serializeAttributes(it.latraccia.entity.anasic.richiesta.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(it.latraccia.entity.anasic.richiesta.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (it.latraccia.entity.anasic.richiesta.RichiestaTypes.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun."
+"msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gramm"
+"ar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expression"
+"\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000bex"
+"pandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq"
+"\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\'com.sun.msv.grammar.trex.E"
+"lementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/"
+"NameClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aig"
+"noreUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003pp\u0000sr\u0000\u001fcom"
+".sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsq\u0000~\u0000\u000fpp\u0000sq\u0000~"
+"\u0000\u0000ppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.s"
+"un.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003sr\u0000\u0011java."
+"lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000 com.sun.msv.grammar.A"
+"ttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\u0010xq\u0000~\u0000\u0003q\u0000~\u0000"
+"\u001bpsr\u00002com.sun.msv.grammar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000\u001a\u0001q\u0000~\u0000\u001fsr\u0000 com.sun.msv.grammar.AnyNameClas"
+"s\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr"
+"\u00000com.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0000xq\u0000~\u0000\u0003q\u0000~\u0000 q\u0000~\u0000%sr\u0000#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012Ljava/lang/String;L\u0000\fnamespaceURIq\u0000~\u0000\'"
+"xq\u0000~\u0000\"t\u0000=it.latraccia.entity.anasic.richiesta.InterrogaAnagr"
+"aficaTypest\u0000+http://java.sun.com/jaxb/xjc/dummy-elementssq\u0000~"
+"\u0000\u0000ppsq\u0000~\u0000\u001cq\u0000~\u0000\u001bpsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000"
+"\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000"
+"\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000\"com.sun.msv.dataty"
+"pe.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.Buil"
+"tinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.Concret"
+"eType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq\u0000~\u0000\'L\u0000\btypeNameq\u0000~\u0000\'L\u0000\nwhiteSpacet"
+"\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://"
+"www.w3.org/2001/XMLSchemat\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xs"
+"d.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.dat"
+"atype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.gr"
+"ammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom"
+".sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\'L\u0000\fnames"
+"paceURIq\u0000~\u0000\'xpq\u0000~\u00008q\u0000~\u00007sq\u0000~\u0000&t\u0000\u0004typet\u0000)http://www.w3.org/20"
+"01/XMLSchema-instanceq\u0000~\u0000%sq\u0000~\u0000&t\u0000\u0013InterrogaAnagraficat\u0000\u0000sq\u0000"
+"~\u0000\u000fpp\u0000sq\u0000~\u0000\u0013ppsq\u0000~\u0000\u000fpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017q\u0000~\u0000\u001bpsq\u0000~\u0000\u001cq\u0000~\u0000\u001bpq\u0000~\u0000\u001f"
+"q\u0000~\u0000#q\u0000~\u0000%sq\u0000~\u0000&t\u0000Fit.latraccia.entity.anasic.richiesta.Inte"
+"rrogaAnagraficaContrattiTypesq\u0000~\u0000*sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u001cq\u0000~\u0000\u001bpq\u0000~\u00000q"
+"\u0000~\u0000@q\u0000~\u0000%sq\u0000~\u0000&t\u0000\u001cInterrogaAnagraficaContrattiq\u0000~\u0000Esq\u0000~\u0000\u000fpp\u0000"
+"sq\u0000~\u0000\u0013ppsq\u0000~\u0000\u000fpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017q\u0000~\u0000\u001bpsq\u0000~\u0000\u001cq\u0000~\u0000\u001bpq\u0000~\u0000\u001fq\u0000~\u0000#q"
+"\u0000~\u0000%sq\u0000~\u0000&t\u0000<it.latraccia.entity.anasic.richiesta.VerificaAn"
+"agraficaTypesq\u0000~\u0000*sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u001cq\u0000~\u0000\u001bpq\u0000~\u00000q\u0000~\u0000@q\u0000~\u0000%sq\u0000~\u0000&t"
+"\u0000\u0012VerificaAnagraficaq\u0000~\u0000Esq\u0000~\u0000\u000fpp\u0000sq\u0000~\u0000\u0013ppsq\u0000~\u0000\u000fpp\u0000sq\u0000~\u0000\u0000pps"
+"q\u0000~\u0000\u0017q\u0000~\u0000\u001bpsq\u0000~\u0000\u001cq\u0000~\u0000\u001bpq\u0000~\u0000\u001fq\u0000~\u0000#q\u0000~\u0000%sq\u0000~\u0000&t\u00008it.latraccia."
+"entity.anasic.richiesta.CreaAnagraficaTypesq\u0000~\u0000*sq\u0000~\u0000\u0000ppsq\u0000~"
+"\u0000\u001cq\u0000~\u0000\u001bpq\u0000~\u00000q\u0000~\u0000@q\u0000~\u0000%sq\u0000~\u0000&t\u0000\u000eCreaAnagraficaq\u0000~\u0000Esq\u0000~\u0000\u000fpp\u0000"
+"sq\u0000~\u0000\u0013ppsq\u0000~\u0000\u000fpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017q\u0000~\u0000\u001bpsq\u0000~\u0000\u001cq\u0000~\u0000\u001bpq\u0000~\u0000\u001fq\u0000~\u0000#q"
+"\u0000~\u0000%sq\u0000~\u0000&t\u00002it.latraccia.entity.anasic.richiesta.CreaSedeTy"
+"pesq\u0000~\u0000*sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u001cq\u0000~\u0000\u001bpq\u0000~\u00000q\u0000~\u0000@q\u0000~\u0000%sq\u0000~\u0000&t\u0000\bCreaSede"
+"q\u0000~\u0000Esq\u0000~\u0000\u000fpp\u0000sq\u0000~\u0000\u0013ppsq\u0000~\u0000\u000fpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017q\u0000~\u0000\u001bpsq\u0000~\u0000\u001cq\u0000~"
+"\u0000\u001bpq\u0000~\u0000\u001fq\u0000~\u0000#q\u0000~\u0000%sq\u0000~\u0000&t\u0000;it.latraccia.entity.anasic.richie"
+"sta.CreaContoBancarioTypesq\u0000~\u0000*sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u001cq\u0000~\u0000\u001bpq\u0000~\u00000q\u0000~\u0000"
+"@q\u0000~\u0000%sq\u0000~\u0000&t\u0000\u0011CreaContoBancarioq\u0000~\u0000Esq\u0000~\u0000\u000fpp\u0000sq\u0000~\u0000\u0013ppsq\u0000~\u0000\u000f"
+"pp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017q\u0000~\u0000\u001bpsq\u0000~\u0000\u001cq\u0000~\u0000\u001bpq\u0000~\u0000\u001fq\u0000~\u0000#q\u0000~\u0000%sq\u0000~\u0000&t\u00009i"
+"t.latraccia.entity.anasic.richiesta.InterrogaComuniTypesq\u0000~\u0000"
+"*sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u001cq\u0000~\u0000\u001bpq\u0000~\u00000q\u0000~\u0000@q\u0000~\u0000%sq\u0000~\u0000&t\u0000\u000fInterrogaComuni"
+"q\u0000~\u0000Esq\u0000~\u0000\u000fpp\u0000sq\u0000~\u0000\u0013ppsq\u0000~\u0000\u000fpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017q\u0000~\u0000\u001bpsq\u0000~\u0000\u001cq\u0000~"
+"\u0000\u001bpq\u0000~\u0000\u001fq\u0000~\u0000#q\u0000~\u0000%sq\u0000~\u0000&t\u0000<it.latraccia.entity.anasic.richie"
+"sta.ModificaAnagraficaTypesq\u0000~\u0000*sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u001cq\u0000~\u0000\u001bpq\u0000~\u00000q\u0000~"
+"\u0000@q\u0000~\u0000%sq\u0000~\u0000&t\u0000\u0012ModificaAnagraficaq\u0000~\u0000Esq\u0000~\u0000\u000fpp\u0000sq\u0000~\u0000\u0013ppsq\u0000~"
+"\u0000\u000fpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017q\u0000~\u0000\u001bpsq\u0000~\u0000\u001cq\u0000~\u0000\u001bpq\u0000~\u0000\u001fq\u0000~\u0000#q\u0000~\u0000%sq\u0000~\u0000&t\u0000"
+"6it.latraccia.entity.anasic.richiesta.ModificaSedeTypesq\u0000~\u0000*"
+"sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u001cq\u0000~\u0000\u001bpq\u0000~\u00000q\u0000~\u0000@q\u0000~\u0000%sq\u0000~\u0000&t\u0000\fModificaSedeq\u0000~\u0000"
+"Esq\u0000~\u0000\u000fpp\u0000sq\u0000~\u0000\u0013ppsq\u0000~\u0000\u000fpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017q\u0000~\u0000\u001bpsq\u0000~\u0000\u001cq\u0000~\u0000\u001bpq"
+"\u0000~\u0000\u001fq\u0000~\u0000#q\u0000~\u0000%sq\u0000~\u0000&t\u0000?it.latraccia.entity.anasic.richiesta."
+"ModificaContoBancarioTypesq\u0000~\u0000*sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u001cq\u0000~\u0000\u001bpq\u0000~\u00000q\u0000~\u0000"
+"@q\u0000~\u0000%sq\u0000~\u0000&t\u0000\u0015ModificaContoBancarioq\u0000~\u0000Esq\u0000~\u0000\u000fpp\u0000sq\u0000~\u0000\u0013ppsq"
+"\u0000~\u0000\u000fpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017q\u0000~\u0000\u001bpsq\u0000~\u0000\u001cq\u0000~\u0000\u001bpq\u0000~\u0000\u001fq\u0000~\u0000#q\u0000~\u0000%sq\u0000~\u0000&"
+"t\u0000@it.latraccia.entity.anasic.richiesta.CaricamentoAnagrafic"
+"heTypesq\u0000~\u0000*sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u001cq\u0000~\u0000\u001bpq\u0000~\u00000q\u0000~\u0000@q\u0000~\u0000%sq\u0000~\u0000&t\u0000\u0016Cari"
+"camentoAnagraficheq\u0000~\u0000Esr\u0000\"com.sun.msv.grammar.ExpressionPoo"
+"l\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionPoo"
+"l$ClosedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$Closed"
+"Hash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/"
+"msv/grammar/ExpressionPool;xp\u0000\u0000\u00006\u0001pq\u0000~\u0000\u000bq\u0000~\u0000\u0016q\u0000~\u0000Iq\u0000~\u0000Uq\u0000~\u0000\u0014"
+"q\u0000~\u0000Gq\u0000~\u0000Sq\u0000~\u0000aq\u0000~\u0000_q\u0000~\u0000mq\u0000~\u0000kq\u0000~\u0000yq\u0000~\u0000wq\u0000~\u0000\u0085q\u0000~\u0000\u0083q\u0000~\u0000\u0091q\u0000~\u0000\u008f"
+"q\u0000~\u0000\bq\u0000~\u0000\u009dq\u0000~\u0000\u009bq\u0000~\u0000\u00a9q\u0000~\u0000\u00a7q\u0000~\u0000\u00b5q\u0000~\u0000\u00b3q\u0000~\u0000\u0007q\u0000~\u0000\u0005q\u0000~\u0000\fq\u0000~\u0000\tq\u0000~\u0000+"
+"q\u0000~\u0000Nq\u0000~\u0000Zq\u0000~\u0000fq\u0000~\u0000rq\u0000~\u0000~q\u0000~\u0000\u008aq\u0000~\u0000\u0096q\u0000~\u0000\u00a2q\u0000~\u0000\u00aeq\u0000~\u0000\u0006q\u0000~\u0000\u00baq\u0000~\u0000\r"
+"q\u0000~\u0000\u0019q\u0000~\u0000Jq\u0000~\u0000Vq\u0000~\u0000bq\u0000~\u0000nq\u0000~\u0000zq\u0000~\u0000\u0086q\u0000~\u0000\u0092q\u0000~\u0000\u009eq\u0000~\u0000\u00aaq\u0000~\u0000\u00b6q\u0000~\u0000\u000e"
+"q\u0000~\u0000\nx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends it.latraccia.entity.anasic.richiesta.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(it.latraccia.entity.anasic.richiesta.impl.runtime.UnmarshallingContext context) {
            super(context, "------------------------");
        }

        protected Unmarshaller(it.latraccia.entity.anasic.richiesta.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return it.latraccia.entity.anasic.richiesta.impl.RichiestaTypesImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  18 :
                        if (("IdAnagrafica" == ___local)&&("" == ___uri)) {
                            _InterrogaAnagrafica = ((it.latraccia.entity.anasic.richiesta.impl.InterrogaAnagraficaTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.InterrogaAnagraficaTypesImpl.class), 19, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("Denominazione" == ___local)&&("" == ___uri)) {
                            _InterrogaAnagrafica = ((it.latraccia.entity.anasic.richiesta.impl.InterrogaAnagraficaTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.InterrogaAnagraficaTypesImpl.class), 19, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("PartitaIva" == ___local)&&("" == ___uri)) {
                            _InterrogaAnagrafica = ((it.latraccia.entity.anasic.richiesta.impl.InterrogaAnagraficaTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.InterrogaAnagraficaTypesImpl.class), 19, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("CodiceFiscale" == ___local)&&("" == ___uri)) {
                            _InterrogaAnagrafica = ((it.latraccia.entity.anasic.richiesta.impl.InterrogaAnagraficaTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.InterrogaAnagraficaTypesImpl.class), 19, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("NumeroContratto" == ___local)&&("" == ___uri)) {
                            _InterrogaAnagrafica = ((it.latraccia.entity.anasic.richiesta.impl.InterrogaAnagraficaTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.InterrogaAnagraficaTypesImpl.class), 19, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  8 :
                        if (("Chiave" == ___local)&&("" == ___uri)) {
                            _InterrogaAnagraficaContratti = ((it.latraccia.entity.anasic.richiesta.impl.InterrogaAnagraficaContrattiTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.InterrogaAnagraficaContrattiTypesImpl.class), 9, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  22 :
                        if (("NomeComune" == ___local)&&("" == ___uri)) {
                            _InterrogaComuni = ((it.latraccia.entity.anasic.richiesta.impl.InterrogaComuniTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.InterrogaComuniTypesImpl.class), 23, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  4 :
                        if (("IdAnagrafica" == ___local)&&("" == ___uri)) {
                            _ModificaContoBancario = ((it.latraccia.entity.anasic.richiesta.impl.ModificaContoBancarioTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.ModificaContoBancarioTypesImpl.class), 5, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  0 :
                        if (("InterrogaAnagrafica" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 18;
                            return ;
                        }
                        if (("InterrogaAnagraficaContratti" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 8;
                            return ;
                        }
                        if (("VerificaAnagrafica" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 6;
                            return ;
                        }
                        if (("CreaAnagrafica" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 12;
                            return ;
                        }
                        if (("CreaSede" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 10;
                            return ;
                        }
                        if (("CreaContoBancario" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 14;
                            return ;
                        }
                        if (("InterrogaComuni" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 22;
                            return ;
                        }
                        if (("ModificaAnagrafica" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 20;
                            return ;
                        }
                        if (("ModificaSede" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 16;
                            return ;
                        }
                        if (("ModificaContoBancario" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 4;
                            return ;
                        }
                        if (("CaricamentoAnagrafiche" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        break;
                    case  16 :
                        if (("IdAnagrafica" == ___local)&&("" == ___uri)) {
                            _ModificaSede = ((it.latraccia.entity.anasic.richiesta.impl.ModificaSedeTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.ModificaSedeTypesImpl.class), 17, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  1 :
                        if (("CodiceFiscaleOperatore" == ___local)&&("" == ___uri)) {
                            _CaricamentoAnagrafiche = ((it.latraccia.entity.anasic.richiesta.impl.CaricamentoAnagraficheTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.CaricamentoAnagraficheTypesImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  10 :
                        if (("IdAnagrafica" == ___local)&&("" == ___uri)) {
                            _CreaSede = ((it.latraccia.entity.anasic.richiesta.impl.CreaSedeTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.CreaSedeTypesImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  14 :
                        if (("IdAnagrafica" == ___local)&&("" == ___uri)) {
                            _CreaContoBancario = ((it.latraccia.entity.anasic.richiesta.impl.CreaContoBancarioTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.CreaContoBancarioTypesImpl.class), 15, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  6 :
                        if (("Anagrafica" == ___local)&&("" == ___uri)) {
                            _VerificaAnagrafica = ((it.latraccia.entity.anasic.richiesta.impl.VerificaAnagraficaTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.VerificaAnagraficaTypesImpl.class), 7, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  12 :
                        if (("Anagrafica" == ___local)&&("" == ___uri)) {
                            _CreaAnagrafica = ((it.latraccia.entity.anasic.richiesta.impl.CreaAnagraficaTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.CreaAnagraficaTypesImpl.class), 13, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  20 :
                        if (("IdAnagrafica" == ___local)&&("" == ___uri)) {
                            _ModificaAnagrafica = ((it.latraccia.entity.anasic.richiesta.impl.ModificaAnagraficaTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.ModificaAnagraficaTypesImpl.class), 21, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  7 :
                        if (("VerificaAnagrafica" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  5 :
                        if (("ModificaContoBancario" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  13 :
                        if (("CreaAnagrafica" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  23 :
                        if (("InterrogaComuni" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("CaricamentoAnagrafiche" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  9 :
                        if (("InterrogaAnagraficaContratti" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  19 :
                        if (("InterrogaAnagrafica" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  21 :
                        if (("ModificaAnagrafica" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  15 :
                        if (("CreaContoBancario" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  11 :
                        if (("CreaSede" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  17 :
                        if (("ModificaSede" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
