//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.28 at 01:25:27 PM CET 
//


package it.latraccia.entity.anasic.richiesta.impl;

public class AnagraficaTypesImpl implements it.latraccia.entity.anasic.richiesta.AnagraficaTypes, com.sun.xml.bind.JAXBObject, it.latraccia.entity.anasic.richiesta.impl.runtime.UnmarshallableObject, it.latraccia.entity.anasic.richiesta.impl.runtime.XMLSerializable, it.latraccia.entity.anasic.richiesta.impl.runtime.ValidatableObject
{

    protected java.lang.String _PartitaIva;
    protected java.lang.String _CognomeLR;
    protected java.lang.String _CodiceFiscale;
    protected java.lang.String _ComuneNSLR;
    protected java.lang.String _Pignoramento;
    protected java.lang.String _ComuneRESLR;
    protected it.latraccia.entity.anasic.richiesta.SedeTypes _Sede;
    protected java.lang.String _NomeLR;
    protected java.lang.String _ComuneNS;
    protected java.util.Calendar _DataNascitaLR;
    protected java.lang.String _Commissioni;
    protected java.lang.String _AltriNomi;
    protected java.lang.String _Nome;
    protected java.lang.String _Sesso;
    protected java.lang.String _NotaPignoramento;
    protected java.lang.String _Denominazione;
    protected java.lang.String _CAPRESLR;
    protected java.util.Calendar _DataNascita;
    protected java.lang.String _TipoAnagrafica;
    protected java.lang.String _SessoLR;
    protected java.lang.String _IndirizzoLR;
    protected java.lang.String _Estero;
    protected it.latraccia.entity.anasic.richiesta.DatiBancariTypes _DatiBancari;
    protected java.lang.String _Cognome;
    protected java.lang.String _CodiceFiscaleLR;
    public final static java.lang.Class version = (it.latraccia.entity.anasic.richiesta.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (it.latraccia.entity.anasic.richiesta.AnagraficaTypes.class);
    }

    public java.lang.String getPartitaIva() {
        return _PartitaIva;
    }

    public void setPartitaIva(java.lang.String value) {
        _PartitaIva = value;
    }

    public java.lang.String getCognomeLR() {
        return _CognomeLR;
    }

    public void setCognomeLR(java.lang.String value) {
        _CognomeLR = value;
    }

    public java.lang.String getCodiceFiscale() {
        return _CodiceFiscale;
    }

    public void setCodiceFiscale(java.lang.String value) {
        _CodiceFiscale = value;
    }

    public java.lang.String getComuneNSLR() {
        return _ComuneNSLR;
    }

    public void setComuneNSLR(java.lang.String value) {
        _ComuneNSLR = value;
    }

    public java.lang.String getPignoramento() {
        return _Pignoramento;
    }

    public void setPignoramento(java.lang.String value) {
        _Pignoramento = value;
    }

    public java.lang.String getComuneRESLR() {
        return _ComuneRESLR;
    }

    public void setComuneRESLR(java.lang.String value) {
        _ComuneRESLR = value;
    }

    public it.latraccia.entity.anasic.richiesta.SedeTypes getSede() {
        return _Sede;
    }

    public void setSede(it.latraccia.entity.anasic.richiesta.SedeTypes value) {
        _Sede = value;
    }

    public java.lang.String getNomeLR() {
        return _NomeLR;
    }

    public void setNomeLR(java.lang.String value) {
        _NomeLR = value;
    }

    public java.lang.String getComuneNS() {
        return _ComuneNS;
    }

    public void setComuneNS(java.lang.String value) {
        _ComuneNS = value;
    }

    public java.util.Calendar getDataNascitaLR() {
        return _DataNascitaLR;
    }

    public void setDataNascitaLR(java.util.Calendar value) {
        _DataNascitaLR = value;
    }

    public java.lang.String getCommissioni() {
        return _Commissioni;
    }

    public void setCommissioni(java.lang.String value) {
        _Commissioni = value;
    }

    public java.lang.String getAltriNomi() {
        return _AltriNomi;
    }

    public void setAltriNomi(java.lang.String value) {
        _AltriNomi = value;
    }

    public java.lang.String getNome() {
        return _Nome;
    }

    public void setNome(java.lang.String value) {
        _Nome = value;
    }

    public java.lang.String getSesso() {
        return _Sesso;
    }

    public void setSesso(java.lang.String value) {
        _Sesso = value;
    }

    public java.lang.String getNotaPignoramento() {
        return _NotaPignoramento;
    }

    public void setNotaPignoramento(java.lang.String value) {
        _NotaPignoramento = value;
    }

    public java.lang.String getDenominazione() {
        return _Denominazione;
    }

    public void setDenominazione(java.lang.String value) {
        _Denominazione = value;
    }

    public java.lang.String getCAPRESLR() {
        return _CAPRESLR;
    }

    public void setCAPRESLR(java.lang.String value) {
        _CAPRESLR = value;
    }

    public java.util.Calendar getDataNascita() {
        return _DataNascita;
    }

    public void setDataNascita(java.util.Calendar value) {
        _DataNascita = value;
    }

    public java.lang.String getTipoAnagrafica() {
        return _TipoAnagrafica;
    }

    public void setTipoAnagrafica(java.lang.String value) {
        _TipoAnagrafica = value;
    }

    public java.lang.String getSessoLR() {
        return _SessoLR;
    }

    public void setSessoLR(java.lang.String value) {
        _SessoLR = value;
    }

    public java.lang.String getIndirizzoLR() {
        return _IndirizzoLR;
    }

    public void setIndirizzoLR(java.lang.String value) {
        _IndirizzoLR = value;
    }

    public java.lang.String getEstero() {
        return _Estero;
    }

    public void setEstero(java.lang.String value) {
        _Estero = value;
    }

    public it.latraccia.entity.anasic.richiesta.DatiBancariTypes getDatiBancari() {
        return _DatiBancari;
    }

    public void setDatiBancari(it.latraccia.entity.anasic.richiesta.DatiBancariTypes value) {
        _DatiBancari = value;
    }

    public java.lang.String getCognome() {
        return _Cognome;
    }

    public void setCognome(java.lang.String value) {
        _Cognome = value;
    }

    public java.lang.String getCodiceFiscaleLR() {
        return _CodiceFiscaleLR;
    }

    public void setCodiceFiscaleLR(java.lang.String value) {
        _CodiceFiscaleLR = value;
    }

    public it.latraccia.entity.anasic.richiesta.impl.runtime.UnmarshallingEventHandler createUnmarshaller(it.latraccia.entity.anasic.richiesta.impl.runtime.UnmarshallingContext context) {
        return new it.latraccia.entity.anasic.richiesta.impl.AnagraficaTypesImpl.Unmarshaller(context);
    }

    public void serializeBody(it.latraccia.entity.anasic.richiesta.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("", "TipoAnagrafica");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _TipoAnagrafica), "TipoAnagrafica");
        } catch (java.lang.Exception e) {
            it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        if (_PartitaIva!= null) {
            context.startElement("", "PartitaIva");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _PartitaIva), "PartitaIva");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_Denominazione!= null) {
            context.startElement("", "Denominazione");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _Denominazione), "Denominazione");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_CognomeLR!= null) {
            context.startElement("", "CognomeLR");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _CognomeLR), "CognomeLR");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_NomeLR!= null) {
            context.startElement("", "NomeLR");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _NomeLR), "NomeLR");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_SessoLR!= null) {
            context.startElement("", "SessoLR");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _SessoLR), "SessoLR");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_ComuneNSLR!= null) {
            context.startElement("", "ComuneNSLR");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _ComuneNSLR), "ComuneNSLR");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_DataNascitaLR!= null) {
            context.startElement("", "DataNascitaLR");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printDate(((java.util.Calendar) _DataNascitaLR)), "DataNascitaLR");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_IndirizzoLR!= null) {
            context.startElement("", "IndirizzoLR");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _IndirizzoLR), "IndirizzoLR");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_ComuneRESLR!= null) {
            context.startElement("", "ComuneRESLR");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _ComuneRESLR), "ComuneRESLR");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_CAPRESLR!= null) {
            context.startElement("", "CAPRESLR");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _CAPRESLR), "CAPRESLR");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_CodiceFiscaleLR!= null) {
            context.startElement("", "CodiceFiscaleLR");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _CodiceFiscaleLR), "CodiceFiscaleLR");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_CodiceFiscale!= null) {
            context.startElement("", "CodiceFiscale");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _CodiceFiscale), "CodiceFiscale");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_Cognome!= null) {
            context.startElement("", "Cognome");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _Cognome), "Cognome");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_Nome!= null) {
            context.startElement("", "Nome");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _Nome), "Nome");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_AltriNomi!= null) {
            context.startElement("", "AltriNomi");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _AltriNomi), "AltriNomi");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_Sesso!= null) {
            context.startElement("", "Sesso");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _Sesso), "Sesso");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_ComuneNS!= null) {
            context.startElement("", "ComuneNS");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _ComuneNS), "ComuneNS");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_DataNascita!= null) {
            context.startElement("", "DataNascita");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printDate(((java.util.Calendar) _DataNascita)), "DataNascita");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_Pignoramento!= null) {
            context.startElement("", "Pignoramento");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _Pignoramento), "Pignoramento");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_NotaPignoramento!= null) {
            context.startElement("", "NotaPignoramento");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _NotaPignoramento), "NotaPignoramento");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_Estero!= null) {
            context.startElement("", "Estero");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _Estero), "Estero");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_Commissioni!= null) {
            context.startElement("", "Commissioni");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _Commissioni), "Commissioni");
            } catch (java.lang.Exception e) {
                it.latraccia.entity.anasic.richiesta.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        context.startElement("", "Sede");
        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Sede), "Sede");
        context.endNamespaceDecls();
        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Sede), "Sede");
        context.endAttributes();
        context.childAsBody(((com.sun.xml.bind.JAXBObject) _Sede), "Sede");
        context.endElement();
        context.startElement("", "DatiBancari");
        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _DatiBancari), "DatiBancari");
        context.endNamespaceDecls();
        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _DatiBancari), "DatiBancari");
        context.endAttributes();
        context.childAsBody(((com.sun.xml.bind.JAXBObject) _DatiBancari), "DatiBancari");
        context.endElement();
    }

    public void serializeAttributes(it.latraccia.entity.anasic.richiesta.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(it.latraccia.entity.anasic.richiesta.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (it.latraccia.entity.anasic.richiesta.AnagraficaTypes.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000pp"
+"sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~"
+"\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000pp"
+"sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\'com.sun.msv.grammar.trex.Element"
+"Pattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameCl"
+"ass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUn"
+"declaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003pp\u0000sq\u0000~\u0000\u0000ppsr\u0000\u001bc"
+"om.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/da"
+"tatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/St"
+"ringPair;xq\u0000~\u0000\u0003ppsr\u0000)com.sun.msv.datatype.xsd.EnumerationFac"
+"et\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0006valuest\u0000\u000fLjava/util/Set;xr\u00009com.sun.msv.data"
+"type.xsd.DataTypeWithValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com."
+"sun.msv.datatype.xsd.DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetF"
+"ixedZ\u0000\u0012needValueCheckFlagL\u0000\bbaseTypet\u0000)Lcom/sun/msv/datatype"
+"/xsd/XSDatatypeImpl;L\u0000\fconcreteTypet\u0000\'Lcom/sun/msv/datatype/"
+"xsd/ConcreteType;L\u0000\tfacetNamet\u0000\u0012Ljava/lang/String;xr\u0000\'com.su"
+"n.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq"
+"\u0000~\u0000,L\u0000\btypeNameq\u0000~\u0000,L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xs"
+"d/WhiteSpaceProcessor;xpt\u0000\u0000psr\u00005com.sun.msv.datatype.xsd.Whi"
+"teSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype"
+".xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0000\u0000sr\u0000#com.sun.msv.datat"
+"ype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv"
+".datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.da"
+"tatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000-t\u0000 http://www.w3.org"
+"/2001/XMLSchemat\u0000\u0006stringq\u0000~\u00003\u0001q\u0000~\u00007t\u0000\u000benumerationsr\u0000\u0011java.ut"
+"il.HashSet\u00baD\u0085\u0095\u0096\u00b8\u00b74\u0003\u0000\u0000xpw\f\u0000\u0000\u0000\u0010?@\u0000\u0000\u0000\u0000\u0000\u0002t\u0000\u0001Ft\u0000\u0001Gxsr\u00000com.sun.ms"
+"v.grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000"
+"\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000,L\u0000\fn"
+"amespaceURIq\u0000~\u0000,xpt\u0000\u000estring-derivedq\u0000~\u00000sr\u0000\u001dcom.sun.msv.gram"
+"mar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000 com.sun.msv.grammar.Attr"
+"ibuteExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\u001exq\u0000~\u0000\u0003sr\u0000\u0011jav"
+"a.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000\"ppsr\u0000\"com.sun.msv"
+".datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u00005q\u0000~\u00008t\u0000\u0005QNamesr\u00005com"
+".sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0000xq\u0000~\u00002q\u0000~\u0000@sq\u0000~\u0000Aq\u0000~\u0000Mq\u0000~\u00008sr\u0000#com.sun.msv.grammar.SimpleNa"
+"meClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000,L\u0000\fnamespaceURIq\u0000~\u0000,xr\u0000\u001dc"
+"om.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)http://ww"
+"w.w3.org/2001/XMLSchema-instancesr\u00000com.sun.msv.grammar.Expr"
+"ession$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000H\u0001q\u0000~\u0000Wsq\u0000~\u0000Qt"
+"\u0000\u000eTipoAnagraficaq\u0000~\u00000sq\u0000~\u0000Dppsq\u0000~\u0000\u001dq\u0000~\u0000Ip\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\"ppsr"
+"\u0000%com.sun.msv.datatype.xsd.PatternFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001[\u0000\bpattern"
+"st\u0000\u0013[Ljava/lang/String;xr\u0000;com.sun.msv.datatype.xsd.DataType"
+"WithLexicalConstraintFacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xq\u0000~\u0000)q\u0000~\u00000pq\u0000~\u00003\u0000\u0000q\u0000~\u0000"
+"7q\u0000~\u00007t\u0000\u0007patternur\u0000\u0013[Ljava.lang.String;\u00ad\u00d2V\u00e7\u00e9\u001d{G\u0002\u0000\u0000xp\u0000\u0000\u0000\u0001t\u0000\u0006\\"
+"d{11}q\u0000~\u0000@sq\u0000~\u0000At\u0000\u000estring-derivedq\u0000~\u00000sq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000~\u0000Ipq\u0000"
+"~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\nPartitaIvaq\u0000~\u00000q\u0000~\u0000Wsq\u0000~\u0000Dppsq\u0000~\u0000\u001dq\u0000~\u0000"
+"Ip\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\"ppq\u0000~\u00007q\u0000~\u0000@sq\u0000~\u0000Aq\u0000~\u00009q\u0000~\u00008sq\u0000~\u0000Dppsq\u0000~\u0000Fq"
+"\u0000~\u0000Ipq\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\rDenominazioneq\u0000~\u00000q\u0000~\u0000Wsq\u0000~\u0000Dpp"
+"sq\u0000~\u0000\u001dq\u0000~\u0000Ip\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000"
+"Wsq\u0000~\u0000Qt\u0000\tCognomeLRq\u0000~\u00000q\u0000~\u0000Wsq\u0000~\u0000Dppsq\u0000~\u0000\u001dq\u0000~\u0000Ip\u0000sq\u0000~\u0000\u0000ppq\u0000"
+"~\u0000psq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\u0006NomeLRq\u0000~\u00000q\u0000"
+"~\u0000Wsq\u0000~\u0000Dppsq\u0000~\u0000\u001dq\u0000~\u0000Ip\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\"ppsq\u0000~\u0000&q\u0000~\u00000pq\u0000~\u00003\u0000\u0000q"
+"\u0000~\u00007q\u0000~\u00007q\u0000~\u0000:sq\u0000~\u0000;w\f\u0000\u0000\u0000\u0010?@\u0000\u0000\u0000\u0000\u0000\u0002t\u0000\u0001Ft\u0000\u0001Mxq\u0000~\u0000@sq\u0000~\u0000At\u0000\u000estr"
+"ing-derivedq\u0000~\u00000sq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\u0007"
+"SessoLRq\u0000~\u00000q\u0000~\u0000Wsq\u0000~\u0000Dppsq\u0000~\u0000\u001dq\u0000~\u0000Ip\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u0000Dpps"
+"q\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\nComuneNSLRq\u0000~\u00000q\u0000~\u0000Wsq\u0000~\u0000"
+"Dppsq\u0000~\u0000\u001dq\u0000~\u0000Ip\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\"ppsr\u0000!com.sun.msv.datatype.xsd"
+".DateType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000)com.sun.msv.datatype.xsd.DateTimeBas"
+"eType\u0014W\u001a@3\u00a5\u00b4\u00e5\u0002\u0000\u0000xq\u0000~\u00005q\u0000~\u00008t\u0000\u0004dateq\u0000~\u0000Oq\u0000~\u0000@sq\u0000~\u0000Aq\u0000~\u0000\u00a0q\u0000~\u00008"
+"sq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\rDataNascitaLRq\u0000~"
+"\u00000q\u0000~\u0000Wsq\u0000~\u0000Dppsq\u0000~\u0000\u001dq\u0000~\u0000Ip\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000~\u0000I"
+"pq\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\u000bIndirizzoLRq\u0000~\u00000q\u0000~\u0000Wsq\u0000~\u0000Dppsq\u0000~\u0000\u001d"
+"q\u0000~\u0000Ip\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000"
+"Qt\u0000\u000bComuneRESLRq\u0000~\u00000q\u0000~\u0000Wsq\u0000~\u0000Dppsq\u0000~\u0000\u001dq\u0000~\u0000Ip\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\""
+"ppsr\u0000\'com.sun.msv.datatype.xsd.MaxLengthFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\tm"
+"axLengthxq\u0000~\u0000(q\u0000~\u00000pq\u0000~\u00003\u0000\u0001sr\u0000\'com.sun.msv.datatype.xsd.MinL"
+"engthFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\tminLengthxq\u0000~\u0000(q\u0000~\u00000pq\u0000~\u00003\u0000\u0000q\u0000~\u00007q\u0000~"
+"\u00007t\u0000\tminLength\u0000\u0000\u0000\u0001q\u0000~\u00007t\u0000\tmaxLength\u0000\u0000\u0000\nq\u0000~\u0000@sq\u0000~\u0000At\u0000\u000estring-"
+"derivedq\u0000~\u00000sq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\bCAPR"
+"ESLRq\u0000~\u00000q\u0000~\u0000Wsq\u0000~\u0000Dppsq\u0000~\u0000\u001dq\u0000~\u0000Ip\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\"ppsq\u0000~\u0000_q\u0000~"
+"\u00000pq\u0000~\u00003\u0000\u0001sq\u0000~\u0000\u00b8q\u0000~\u00000pq\u0000~\u00003\u0000\u0001sq\u0000~\u0000\u00baq\u0000~\u00000pq\u0000~\u00003\u0000\u0000q\u0000~\u00007q\u0000~\u00007q\u0000"
+"~\u0000\u00bc\u0000\u0000\u0000\u0010q\u0000~\u00007q\u0000~\u0000\u00bd\u0000\u0000\u0000\u0010q\u0000~\u00007q\u0000~\u0000cuq\u0000~\u0000d\u0000\u0000\u0000\u0001t\u0000\u0011([a-zA-Z0-9]){16"
+"}q\u0000~\u0000@sq\u0000~\u0000At\u0000\u000estring-derivedq\u0000~\u00000sq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~\u0000Jq"
+"\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\u000fCodiceFiscaleLRq\u0000~\u00000q\u0000~\u0000Wsq\u0000~\u0000Dppsq\u0000~\u0000\u001dq\u0000~"
+"\u0000Ip\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\"ppsq\u0000~\u0000_q\u0000~\u00000pq\u0000~\u00003\u0000\u0001sq\u0000~\u0000\u00b8q\u0000~\u00000pq\u0000~\u00003\u0000\u0001sq"
+"\u0000~\u0000\u00baq\u0000~\u00000pq\u0000~\u00003\u0000\u0000q\u0000~\u00007q\u0000~\u00007q\u0000~\u0000\u00bc\u0000\u0000\u0000\u0010q\u0000~\u00007q\u0000~\u0000\u00bd\u0000\u0000\u0000\u0010q\u0000~\u00007q\u0000~\u0000c"
+"uq\u0000~\u0000d\u0000\u0000\u0000\u0001t\u0000\u0011([a-zA-Z0-9]){16}q\u0000~\u0000@sq\u0000~\u0000At\u0000\u000estring-derivedq\u0000"
+"~\u00000sq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\rCodiceFiscale"
+"q\u0000~\u00000q\u0000~\u0000Wsq\u0000~\u0000Dppsq\u0000~\u0000\u001dq\u0000~\u0000Ip\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000"
+"~\u0000Ipq\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\u0007Cognomeq\u0000~\u00000q\u0000~\u0000Wsq\u0000~\u0000Dppsq\u0000~\u0000\u001dq"
+"\u0000~\u0000Ip\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Q"
+"t\u0000\u0004Nomeq\u0000~\u00000q\u0000~\u0000Wsq\u0000~\u0000Dppsq\u0000~\u0000\u001dq\u0000~\u0000Ip\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u0000Dpps"
+"q\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\tAltriNomiq\u0000~\u00000q\u0000~\u0000Wsq\u0000~\u0000D"
+"ppsq\u0000~\u0000\u001dq\u0000~\u0000Ip\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\"ppsq\u0000~\u0000&q\u0000~\u00000pq\u0000~\u00003\u0000\u0000q\u0000~\u00007q\u0000~\u00007"
+"q\u0000~\u0000:sq\u0000~\u0000;w\f\u0000\u0000\u0000\u0010?@\u0000\u0000\u0000\u0000\u0000\u0002t\u0000\u0001Ft\u0000\u0001Mxq\u0000~\u0000@sq\u0000~\u0000At\u0000\u000estring-deriv"
+"edq\u0000~\u00000sq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\u0005Sessoq\u0000~\u0000"
+"0q\u0000~\u0000Wsq\u0000~\u0000Dppsq\u0000~\u0000\u001dq\u0000~\u0000Ip\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000~\u0000Ip"
+"q\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\bComuneNSq\u0000~\u00000q\u0000~\u0000Wsq\u0000~\u0000Dppsq\u0000~\u0000\u001dq\u0000~\u0000"
+"Ip\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u009csq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\u000b"
+"DataNascitaq\u0000~\u00000q\u0000~\u0000Wsq\u0000~\u0000Dppsq\u0000~\u0000\u001dq\u0000~\u0000Ip\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\"ppsq"
+"\u0000~\u0000&q\u0000~\u00000pq\u0000~\u00003\u0000\u0000q\u0000~\u00007q\u0000~\u00007q\u0000~\u0000:sq\u0000~\u0000;w\f\u0000\u0000\u0000\u0010?@\u0000\u0000\u0000\u0000\u0000\u0002t\u0000\u0001St\u0000\u0001N"
+"xq\u0000~\u0000@sq\u0000~\u0000At\u0000\u000estring-derivedq\u0000~\u00000sq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~\u0000Jq"
+"\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\fPignoramentoq\u0000~\u00000q\u0000~\u0000Wsq\u0000~\u0000Dppsq\u0000~\u0000\u001dq\u0000~\u0000Ip"
+"\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\u0010No"
+"taPignoramentoq\u0000~\u00000q\u0000~\u0000Wsq\u0000~\u0000Dppsq\u0000~\u0000\u001dq\u0000~\u0000Ip\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\"p"
+"psq\u0000~\u0000&q\u0000~\u00000pq\u0000~\u00003\u0000\u0000q\u0000~\u00007q\u0000~\u00007q\u0000~\u0000:sq\u0000~\u0000;w\f\u0000\u0000\u0000\u0010?@\u0000\u0000\u0000\u0000\u0000\u0002t\u0000\u0001St"
+"\u0000\u0001Nxq\u0000~\u0000@sq\u0000~\u0000At\u0000\u000estring-derivedq\u0000~\u00000sq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~"
+"\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\u0006Esteroq\u0000~\u00000q\u0000~\u0000Wsq\u0000~\u0000Dppsq\u0000~\u0000\u001dq\u0000~\u0000Ip\u0000sq"
+"\u0000~\u0000\u0000ppsq\u0000~\u0000\"ppsq\u0000~\u0000&q\u0000~\u00000pq\u0000~\u00003\u0000\u0000q\u0000~\u00007q\u0000~\u00007q\u0000~\u0000:sq\u0000~\u0000;w\f\u0000\u0000\u0000\u0010"
+"?@\u0000\u0000\u0000\u0000\u0000\u0003t\u0000\u0001St\u0000\u0001Et\u0000\u0001Nxq\u0000~\u0000@sq\u0000~\u0000At\u0000\u000estring-derivedq\u0000~\u00000sq\u0000~\u0000D"
+"ppsq\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\u000bCommissioniq\u0000~\u00000q\u0000~\u0000Ws"
+"q\u0000~\u0000\u001dpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u001dpp\u0000sq\u0000~\u0000Dppsr\u0000 com.sun.msv.grammar.One"
+"OrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003q\u0000~\u0000Ipsq\u0000~\u0000Fq\u0000~\u0000Ipsr\u00002com.sun.msv.gramma"
+"r.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000Xq\u0000~\u0001Ns"
+"r\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000Rq\u0000~\u0000Wsq\u0000"
+"~\u0000Qt\u0000.it.latraccia.entity.anasic.richiesta.SedeTypest\u0000+http:"
+"//java.sun.com/jaxb/xjc/dummy-elementssq\u0000~\u0000Dppsq\u0000~\u0000Fq\u0000~\u0000Ipq\u0000"
+"~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\u0004Sedeq\u0000~\u00000sq\u0000~\u0000\u001dpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u001dpp\u0000sq\u0000"
+"~\u0000Dppsq\u0000~\u0001Iq\u0000~\u0000Ipsq\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~\u0001Nq\u0000~\u0001Pq\u0000~\u0000Wsq\u0000~\u0000Qt\u00005it.latr"
+"accia.entity.anasic.richiesta.DatiBancariTypesq\u0000~\u0001Ssq\u0000~\u0000Dpps"
+"q\u0000~\u0000Fq\u0000~\u0000Ipq\u0000~\u0000Jq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\u000bDatiBancariq\u0000~\u00000sr\u0000\"com.s"
+"un.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/s"
+"un/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.g"
+"rammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstream"
+"VersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000"
+"d\u0001pq\u0000~\u0000\nq\u0000~\u0000\rq\u0000~\u0001(q\u0000~\u0000]q\u0000~\u0000\u00f9q\u0000~\u0000\u0006q\u0000~\u0000\u009bq\u0000~\u0001\u000eq\u0000~\u0001\u0013q\u0000~\u0000\u0015q\u0000~\u0000\u0014q\u0000"
+"~\u0000[q\u0000~\u0000\u000fq\u0000~\u0000\u0099q\u0000~\u0001\fq\u0000~\u0000\bq\u0000~\u0000\u0010q\u0000~\u0000\u00c4q\u0000~\u0000\u00ecq\u0000~\u0000\u00e5q\u0000~\u0000\u00deq\u0000~\u0000\u00cfq\u0000~\u0000\u00c0q\u0000"
+"~\u0000\u00b0q\u0000~\u0000\u00a9q\u0000~\u0000\u00a2q\u0000~\u0000\u0095q\u0000~\u0000\u0017q\u0000~\u0000\u008eq\u0000~\u0000\u0080q\u0000~\u0000yq\u0000~\u0000rq\u0000~\u0000iq\u0000~\u0000\u0019q\u0000~\u0000Eq\u0000"
+"~\u0000\u00f3q\u0000~\u0001\u0001q\u0000~\u0001\bq\u0000~\u0001\u000fq\u0000~\u0000\u0086q\u0000~\u0000\u000bq\u0000~\u0001\u001dq\u0000~\u0001$q\u0000~\u0000\u0011q\u0000~\u00012q\u0000~\u0001Aq\u0000~\u0001Tq\u0000"
+"~\u0001`q\u0000~\u0000\u0084q\u0000~\u0001Kq\u0000~\u0001\\q\u0000~\u0000\u0012q\u0000~\u0000\fq\u0000~\u0000\u00d3q\u0000~\u0000\u001cq\u0000~\u0001Hq\u0000~\u0001[q\u0000~\u0000\u0016q\u0000~\u0000\u00ebq\u0000"
+"~\u0000\u00e4q\u0000~\u0000\u00afq\u0000~\u0000\u00a8q\u0000~\u0000\u0094q\u0000~\u0000\u007fq\u0000~\u0000xq\u0000~\u0000oq\u0000~\u0000\u00c6q\u0000~\u0000\u0013q\u0000~\u0000\u00f2q\u0000~\u0001\u0007q\u0000~\u0001#q\u0000"
+"~\u0001Fq\u0000~\u0001Yq\u0000~\u0000\u0005q\u0000~\u0000\u000eq\u0000~\u00018q\u0000~\u0000\u00d5q\u0000~\u0000\u00b6q\u0000~\u0000\u001bq\u0000~\u0000\u0007q\u0000~\u0001\u0015q\u0000~\u0000!q\u0000~\u0000\u00e9q\u0000"
+"~\u0000\u00e2q\u0000~\u0000\u00adq\u0000~\u0000\u00a6q\u0000~\u0000\u0092q\u0000~\u0000}q\u0000~\u0000vq\u0000~\u0000\u00b4q\u0000~\u0000mq\u0000~\u0000\u00f0q\u0000~\u0001\u0005q\u0000~\u0001!q\u0000~\u0000\u0018q\u0000"
+"~\u0000\tq\u0000~\u00016q\u0000~\u0001*q\u0000~\u0000\u00f7q\u0000~\u0000\u001ax"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends it.latraccia.entity.anasic.richiesta.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(it.latraccia.entity.anasic.richiesta.impl.runtime.UnmarshallingContext context) {
            super(context, "----------------------------------------------------------------------------");
        }

        protected Unmarshaller(it.latraccia.entity.anasic.richiesta.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return it.latraccia.entity.anasic.richiesta.impl.AnagraficaTypesImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        if (("PartitaIva" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 4;
                            return ;
                        }
                        state = 6;
                        continue outer;
                    case  72 :
                        if (("DatiBancari" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 73;
                            return ;
                        }
                        break;
                    case  75 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  69 :
                        if (("Sede" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 70;
                            return ;
                        }
                        break;
                    case  73 :
                        if (("NomeBanca" == ___local)&&("" == ___uri)) {
                            _DatiBancari = ((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl.class), 74, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("ContoCorrente" == ___local)&&("" == ___uri)) {
                            _DatiBancari = ((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl.class), 74, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("ModalitaPrincipale" == ___local)&&("" == ___uri)) {
                            _DatiBancari = ((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl.class), 74, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("SedeAgenzia" == ___local)&&("" == ___uri)) {
                            _DatiBancari = ((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl.class), 74, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("Indirizzo" == ___local)&&("" == ___uri)) {
                            _DatiBancari = ((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl.class), 74, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("Citta" == ___local)&&("" == ___uri)) {
                            _DatiBancari = ((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl.class), 74, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("CAP" == ___local)&&("" == ___uri)) {
                            _DatiBancari = ((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl.class), 74, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("Provincia" == ___local)&&("" == ___uri)) {
                            _DatiBancari = ((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl.class), 74, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("ABI" == ___local)&&("" == ___uri)) {
                            _DatiBancari = ((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl.class), 74, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("CAB" == ___local)&&("" == ___uri)) {
                            _DatiBancari = ((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl.class), 74, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("CIN" == ___local)&&("" == ___uri)) {
                            _DatiBancari = ((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl.class), 74, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("IBAN" == ___local)&&("" == ___uri)) {
                            _DatiBancari = ((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl.class), 74, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _DatiBancari = ((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl.class), 74, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  30 :
                        if (("CAPRESLR" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 31;
                            return ;
                        }
                        state = 33;
                        continue outer;
                    case  15 :
                        if (("SessoLR" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 16;
                            return ;
                        }
                        state = 18;
                        continue outer;
                    case  66 :
                        if (("Commissioni" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 67;
                            return ;
                        }
                        state = 69;
                        continue outer;
                    case  51 :
                        if (("ComuneNS" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 52;
                            return ;
                        }
                        state = 54;
                        continue outer;
                    case  21 :
                        if (("DataNascitaLR" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 22;
                            return ;
                        }
                        state = 24;
                        continue outer;
                    case  54 :
                        if (("DataNascita" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 55;
                            return ;
                        }
                        state = 57;
                        continue outer;
                    case  63 :
                        if (("Estero" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 64;
                            return ;
                        }
                        state = 66;
                        continue outer;
                    case  48 :
                        if (("Sesso" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 49;
                            return ;
                        }
                        state = 51;
                        continue outer;
                    case  45 :
                        if (("AltriNomi" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 46;
                            return ;
                        }
                        state = 48;
                        continue outer;
                    case  6 :
                        if (("Denominazione" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 7;
                            return ;
                        }
                        state = 9;
                        continue outer;
                    case  18 :
                        if (("ComuneNSLR" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 19;
                            return ;
                        }
                        state = 21;
                        continue outer;
                    case  42 :
                        if (("Nome" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 43;
                            return ;
                        }
                        state = 45;
                        continue outer;
                    case  60 :
                        if (("NotaPignoramento" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 61;
                            return ;
                        }
                        state = 63;
                        continue outer;
                    case  57 :
                        if (("Pignoramento" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 58;
                            return ;
                        }
                        state = 60;
                        continue outer;
                    case  0 :
                        if (("TipoAnagrafica" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 1;
                            return ;
                        }
                        break;
                    case  9 :
                        if (("CognomeLR" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 10;
                            return ;
                        }
                        state = 12;
                        continue outer;
                    case  70 :
                        if (("Indirizzo" == ___local)&&("" == ___uri)) {
                            _Sede = ((it.latraccia.entity.anasic.richiesta.impl.SedeTypesImpl) spawnChildFromEnterElement((it.latraccia.entity.anasic.richiesta.impl.SedeTypesImpl.class), 71, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  36 :
                        if (("CodiceFiscale" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 37;
                            return ;
                        }
                        state = 39;
                        continue outer;
                    case  27 :
                        if (("ComuneRESLR" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 28;
                            return ;
                        }
                        state = 30;
                        continue outer;
                    case  39 :
                        if (("Cognome" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 40;
                            return ;
                        }
                        state = 42;
                        continue outer;
                    case  33 :
                        if (("CodiceFiscaleLR" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 34;
                            return ;
                        }
                        state = 36;
                        continue outer;
                    case  24 :
                        if (("IndirizzoLR" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 25;
                            return ;
                        }
                        state = 27;
                        continue outer;
                    case  12 :
                        if (("NomeLR" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 13;
                            return ;
                        }
                        state = 15;
                        continue outer;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        state = 6;
                        continue outer;
                    case  75 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  73 :
                        _DatiBancari = ((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl) spawnChildFromLeaveElement((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl.class), 74, ___uri, ___local, ___qname));
                        return ;
                    case  30 :
                        state = 33;
                        continue outer;
                    case  53 :
                        if (("ComuneNS" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 54;
                            return ;
                        }
                        break;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  66 :
                        state = 69;
                        continue outer;
                    case  51 :
                        state = 54;
                        continue outer;
                    case  56 :
                        if (("DataNascita" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 57;
                            return ;
                        }
                        break;
                    case  21 :
                        state = 24;
                        continue outer;
                    case  54 :
                        state = 57;
                        continue outer;
                    case  32 :
                        if (("CAPRESLR" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 33;
                            return ;
                        }
                        break;
                    case  20 :
                        if (("ComuneNSLR" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 21;
                            return ;
                        }
                        break;
                    case  63 :
                        state = 66;
                        continue outer;
                    case  48 :
                        state = 51;
                        continue outer;
                    case  44 :
                        if (("Nome" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 45;
                            return ;
                        }
                        break;
                    case  45 :
                        state = 48;
                        continue outer;
                    case  50 :
                        if (("Sesso" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 51;
                            return ;
                        }
                        break;
                    case  74 :
                        if (("DatiBancari" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 75;
                            return ;
                        }
                        break;
                    case  8 :
                        if (("Denominazione" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  18 :
                        state = 21;
                        continue outer;
                    case  38 :
                        if (("CodiceFiscale" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 39;
                            return ;
                        }
                        break;
                    case  65 :
                        if (("Estero" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 66;
                            return ;
                        }
                        break;
                    case  42 :
                        state = 45;
                        continue outer;
                    case  14 :
                        if (("NomeLR" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 15;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("TipoAnagrafica" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  71 :
                        if (("Sede" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 72;
                            return ;
                        }
                        break;
                    case  60 :
                        state = 63;
                        continue outer;
                    case  57 :
                        state = 60;
                        continue outer;
                    case  23 :
                        if (("DataNascitaLR" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 24;
                            return ;
                        }
                        break;
                    case  9 :
                        state = 12;
                        continue outer;
                    case  36 :
                        state = 39;
                        continue outer;
                    case  68 :
                        if (("Commissioni" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 69;
                            return ;
                        }
                        break;
                    case  41 :
                        if (("Cognome" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 42;
                            return ;
                        }
                        break;
                    case  62 :
                        if (("NotaPignoramento" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 63;
                            return ;
                        }
                        break;
                    case  59 :
                        if (("Pignoramento" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 60;
                            return ;
                        }
                        break;
                    case  27 :
                        state = 30;
                        continue outer;
                    case  39 :
                        state = 42;
                        continue outer;
                    case  26 :
                        if (("IndirizzoLR" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 27;
                            return ;
                        }
                        break;
                    case  17 :
                        if (("SessoLR" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 18;
                            return ;
                        }
                        break;
                    case  33 :
                        state = 36;
                        continue outer;
                    case  35 :
                        if (("CodiceFiscaleLR" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 36;
                            return ;
                        }
                        break;
                    case  5 :
                        if (("PartitaIva" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                    case  24 :
                        state = 27;
                        continue outer;
                    case  12 :
                        state = 15;
                        continue outer;
                    case  29 :
                        if (("ComuneRESLR" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 30;
                            return ;
                        }
                        break;
                    case  47 :
                        if (("AltriNomi" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 48;
                            return ;
                        }
                        break;
                    case  11 :
                        if (("CognomeLR" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 12;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        state = 6;
                        continue outer;
                    case  75 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  73 :
                        _DatiBancari = ((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl) spawnChildFromEnterAttribute((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl.class), 74, ___uri, ___local, ___qname));
                        return ;
                    case  30 :
                        state = 33;
                        continue outer;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  66 :
                        state = 69;
                        continue outer;
                    case  51 :
                        state = 54;
                        continue outer;
                    case  21 :
                        state = 24;
                        continue outer;
                    case  54 :
                        state = 57;
                        continue outer;
                    case  63 :
                        state = 66;
                        continue outer;
                    case  48 :
                        state = 51;
                        continue outer;
                    case  45 :
                        state = 48;
                        continue outer;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  18 :
                        state = 21;
                        continue outer;
                    case  42 :
                        state = 45;
                        continue outer;
                    case  60 :
                        state = 63;
                        continue outer;
                    case  57 :
                        state = 60;
                        continue outer;
                    case  9 :
                        state = 12;
                        continue outer;
                    case  36 :
                        state = 39;
                        continue outer;
                    case  27 :
                        state = 30;
                        continue outer;
                    case  39 :
                        state = 42;
                        continue outer;
                    case  33 :
                        state = 36;
                        continue outer;
                    case  24 :
                        state = 27;
                        continue outer;
                    case  12 :
                        state = 15;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        state = 6;
                        continue outer;
                    case  75 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  73 :
                        _DatiBancari = ((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl) spawnChildFromLeaveAttribute((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl.class), 74, ___uri, ___local, ___qname));
                        return ;
                    case  30 :
                        state = 33;
                        continue outer;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  66 :
                        state = 69;
                        continue outer;
                    case  51 :
                        state = 54;
                        continue outer;
                    case  21 :
                        state = 24;
                        continue outer;
                    case  54 :
                        state = 57;
                        continue outer;
                    case  63 :
                        state = 66;
                        continue outer;
                    case  48 :
                        state = 51;
                        continue outer;
                    case  45 :
                        state = 48;
                        continue outer;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  18 :
                        state = 21;
                        continue outer;
                    case  42 :
                        state = 45;
                        continue outer;
                    case  60 :
                        state = 63;
                        continue outer;
                    case  57 :
                        state = 60;
                        continue outer;
                    case  9 :
                        state = 12;
                        continue outer;
                    case  36 :
                        state = 39;
                        continue outer;
                    case  27 :
                        state = 30;
                        continue outer;
                    case  39 :
                        state = 42;
                        continue outer;
                    case  33 :
                        state = 36;
                        continue outer;
                    case  24 :
                        state = 27;
                        continue outer;
                    case  12 :
                        state = 15;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  3 :
                            state = 6;
                            continue outer;
                        case  75 :
                            revertToParentFromText(value);
                            return ;
                        case  61 :
                            state = 62;
                            eatText1(value);
                            return ;
                        case  40 :
                            state = 41;
                            eatText2(value);
                            return ;
                        case  73 :
                            _DatiBancari = ((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl) spawnChildFromText((it.latraccia.entity.anasic.richiesta.impl.DatiBancariTypesImpl.class), 74, value));
                            return ;
                        case  13 :
                            state = 14;
                            eatText3(value);
                            return ;
                        case  30 :
                            state = 33;
                            continue outer;
                        case  15 :
                            state = 18;
                            continue outer;
                        case  66 :
                            state = 69;
                            continue outer;
                        case  51 :
                            state = 54;
                            continue outer;
                        case  52 :
                            state = 53;
                            eatText4(value);
                            return ;
                        case  4 :
                            state = 5;
                            eatText5(value);
                            return ;
                        case  16 :
                            state = 17;
                            eatText6(value);
                            return ;
                        case  21 :
                            state = 24;
                            continue outer;
                        case  54 :
                            state = 57;
                            continue outer;
                        case  28 :
                            state = 29;
                            eatText7(value);
                            return ;
                        case  43 :
                            state = 44;
                            eatText8(value);
                            return ;
                        case  37 :
                            state = 38;
                            eatText9(value);
                            return ;
                        case  63 :
                            state = 66;
                            continue outer;
                        case  48 :
                            state = 51;
                            continue outer;
                        case  67 :
                            state = 68;
                            eatText10(value);
                            return ;
                        case  45 :
                            state = 48;
                            continue outer;
                        case  31 :
                            state = 32;
                            eatText11(value);
                            return ;
                        case  6 :
                            state = 9;
                            continue outer;
                        case  18 :
                            state = 21;
                            continue outer;
                        case  25 :
                            state = 26;
                            eatText12(value);
                            return ;
                        case  42 :
                            state = 45;
                            continue outer;
                        case  60 :
                            state = 63;
                            continue outer;
                        case  57 :
                            state = 60;
                            continue outer;
                        case  34 :
                            state = 35;
                            eatText13(value);
                            return ;
                        case  9 :
                            state = 12;
                            continue outer;
                        case  7 :
                            state = 8;
                            eatText14(value);
                            return ;
                        case  36 :
                            state = 39;
                            continue outer;
                        case  58 :
                            state = 59;
                            eatText15(value);
                            return ;
                        case  64 :
                            state = 65;
                            eatText16(value);
                            return ;
                        case  55 :
                            state = 56;
                            eatText17(value);
                            return ;
                        case  27 :
                            state = 30;
                            continue outer;
                        case  39 :
                            state = 42;
                            continue outer;
                        case  22 :
                            state = 23;
                            eatText18(value);
                            return ;
                        case  10 :
                            state = 11;
                            eatText19(value);
                            return ;
                        case  1 :
                            state = 2;
                            eatText20(value);
                            return ;
                        case  33 :
                            state = 36;
                            continue outer;
                        case  49 :
                            state = 50;
                            eatText21(value);
                            return ;
                        case  24 :
                            state = 27;
                            continue outer;
                        case  12 :
                            state = 15;
                            continue outer;
                        case  19 :
                            state = 20;
                            eatText22(value);
                            return ;
                        case  46 :
                            state = 47;
                            eatText23(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _NotaPignoramento = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Cognome = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _NomeLR = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _ComuneNS = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText5(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _PartitaIva = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText6(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _SessoLR = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText7(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _ComuneRESLR = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText8(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Nome = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText9(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _CodiceFiscale = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText10(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Commissioni = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText11(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _CAPRESLR = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText12(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _IndirizzoLR = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText13(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _CodiceFiscaleLR = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText14(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Denominazione = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText15(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Pignoramento = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText16(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Estero = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText17(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DataNascita = javax.xml.bind.DatatypeConverter.parseDate(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText18(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DataNascitaLR = javax.xml.bind.DatatypeConverter.parseDate(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText19(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _CognomeLR = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText20(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _TipoAnagrafica = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText21(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Sesso = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText22(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _ComuneNSLR = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText23(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _AltriNomi = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
