//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.28 at 01:25:27 PM CET 
//


package it.latraccia.entity.anasic.richiesta;


/**
 * Java content class for CaricamentoAnagrafiche_Types complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/simonebrunox/Desktop/JAXB/XSD/Anagraf/RichiestaAnaSIC.xsd line 1036)
 * <p>
 * <pre>
 * &lt;complexType name="CaricamentoAnagrafiche_Types">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodiceFiscaleOperatore">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="([a-zA-Z0-9]){16}"/>
 *             &lt;minLength value="16"/>
 *             &lt;maxLength value="16"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="AnagraficaMassiva">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ElementoAnagraficaMassiva" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="IdAnagraficaMittente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Anagrafica" type="{}Anagrafica_Types"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface CaricamentoAnagraficheTypes {


    /**
     * Gets the value of the anagraficaMassiva property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.anasic.richiesta.CaricamentoAnagraficheTypes.AnagraficaMassivaType}
     */
    it.latraccia.entity.anasic.richiesta.CaricamentoAnagraficheTypes.AnagraficaMassivaType getAnagraficaMassiva();

    /**
     * Sets the value of the anagraficaMassiva property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.anasic.richiesta.CaricamentoAnagraficheTypes.AnagraficaMassivaType}
     */
    void setAnagraficaMassiva(it.latraccia.entity.anasic.richiesta.CaricamentoAnagraficheTypes.AnagraficaMassivaType value);

    /**
     * Codice Fiscale dell'utente del sistema che sta effettuando l'operazione
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCodiceFiscaleOperatore();

    /**
     * Codice Fiscale dell'utente del sistema che sta effettuando l'operazione
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCodiceFiscaleOperatore(java.lang.String value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/simonebrunox/Desktop/JAXB/XSD/Anagraf/RichiestaAnaSIC.xsd line 1051)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ElementoAnagraficaMassiva" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="IdAnagraficaMittente" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Anagrafica" type="{}Anagrafica_Types"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface AnagraficaMassivaType {


        /**
         * Gets the value of the ElementoAnagraficaMassiva property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ElementoAnagraficaMassiva property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getElementoAnagraficaMassiva().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link it.latraccia.entity.anasic.richiesta.CaricamentoAnagraficheTypes.AnagraficaMassivaType.ElementoAnagraficaMassivaType}
         * 
         */
        java.util.List getElementoAnagraficaMassiva();


        /**
         * Java content class for anonymous complex type.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/simonebrunox/Desktop/JAXB/XSD/Anagraf/RichiestaAnaSIC.xsd line 1054)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="IdAnagraficaMittente" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Anagrafica" type="{}Anagrafica_Types"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface ElementoAnagraficaMassivaType {


            /**
             * Anagrafica da caricare/aggiornare
             * 
             * @return
             *     possible object is
             *     {@link it.latraccia.entity.anasic.richiesta.AnagraficaTypes}
             */
            it.latraccia.entity.anasic.richiesta.AnagraficaTypes getAnagrafica();

            /**
             * Anagrafica da caricare/aggiornare
             * 
             * @param value
             *     allowed object is
             *     {@link it.latraccia.entity.anasic.richiesta.AnagraficaTypes}
             */
            void setAnagrafica(it.latraccia.entity.anasic.richiesta.AnagraficaTypes value);

            /**
             * Identificativo utilizzato dal mittente per individuare l'anagrafica inviata
             * 
             * @return
             *     possible object is
             *     {@link java.lang.String}
             */
            java.lang.String getIdAnagraficaMittente();

            /**
             * Identificativo utilizzato dal mittente per individuare l'anagrafica inviata
             * 
             * @param value
             *     allowed object is
             *     {@link java.lang.String}
             */
            void setIdAnagraficaMittente(java.lang.String value);

        }

    }

}
