//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.17 at 12:28:37 PM CET 
//


package it.latraccia.entity.sic.risposta;


/**
 * Java content class for Risposta_CreateDelDocumento_Types complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/simonebrunox/Desktop/SIC/RispostaSIC.xsd line 507)
 * <p>
 * <pre>
 * &lt;complexType name="Risposta_CreateDelDocumento_Types">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumeroDocumento" minOccurs="0">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-9]{9}"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="NumeroDocumento_Plur1" minOccurs="0">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-9]{9}"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="NumeroDocumento_Plur2" minOccurs="0">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-9]{9}"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="NumeroStorno" minOccurs="0">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-9]{9}"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="DocId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="DocId1" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="DocId2" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Messaggio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface RispostaCreateDelDocumentoTypes {


    /**
     * Gets the value of the docId property.
     * 
     */
    int getDocId();

    /**
     * Sets the value of the docId property.
     * 
     */
    void setDocId(int value);

    /**
     * Gets the value of the messaggio property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMessaggio();

    /**
     * Sets the value of the messaggio property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMessaggio(java.lang.String value);

    /**
     * Numero del documento generato/eliminato/di variazione/sostituito Pluriennale 1
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getNumeroDocumentoPlur1();

    /**
     * Numero del documento generato/eliminato/di variazione/sostituito Pluriennale 1
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setNumeroDocumentoPlur1(java.lang.String value);

    /**
     * Numero del documento generato/eliminato/di variazione/sostituito Pluriennale 2
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getNumeroDocumentoPlur2();

    /**
     * Numero del documento generato/eliminato/di variazione/sostituito Pluriennale 2
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setNumeroDocumentoPlur2(java.lang.String value);

    /**
     * Numero del documento di storno nel caso di sostituzione (opzionale)
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getNumeroStorno();

    /**
     * Numero del documento di storno nel caso di sostituzione (opzionale)
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setNumeroStorno(java.lang.String value);

    /**
     * Gets the value of the docId2 property.
     * 
     */
    int getDocId2();

    /**
     * Sets the value of the docId2 property.
     * 
     */
    void setDocId2(int value);

    /**
     * Gets the value of the docId1 property.
     * 
     */
    int getDocId1();

    /**
     * Sets the value of the docId1 property.
     * 
     */
    void setDocId1(int value);

    /**
     * Numero del documento generato/eliminato/di variazione/sostituito
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getNumeroDocumento();

    /**
     * Numero del documento generato/eliminato/di variazione/sostituito
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setNumeroDocumento(java.lang.String value);

}
