//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.17 at 12:28:37 PM CET 
//


package it.latraccia.entity.sic.risposta;


/**
 * Java content class for Successo_Types complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/simonebrunox/Desktop/SIC/RispostaSIC.xsd line 62)
 * <p>
 * <pre>
 * &lt;complexType name="Successo_Types">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Risposta_InterrogazioneCapitoli" type="{}Risposta_InterrogazioneCapitoli_Types"/>
 *         &lt;element name="Risposta_InterrogazioneCapitoliLiquidazioni" type="{}Risposta_InterrogazioneCapitoli_Types"/>
 *         &lt;element name="Risposta_InterrogazioneBilancio" type="{}Risposta_InterrogazioneBilancio_Types"/>
 *         &lt;element name="Risposta_InterrogazioneObiettiviGestionali" type="{}Risposta_InterrogazioneObiettiviGestionali_Types"/>
 *         &lt;element name="Risposta_DisponibilitaPreImpegno" type="{}Risposta_DisponibilitaPreImpegno_Types"/>
 *         &lt;element name="Risposta_InterrogazionePreimpegniAperti" type="{}Risposta_InterrogazionePreimpegniAperti_Types"/>
 *         &lt;element name="Risposta_InterrogazioneImpegniAperti" type="{}Risposta_InterrogazioneImpegniAperti_Types"/>
 *         &lt;element name="Risposta_InterrogazioneLiquidazioniAperte" type="{}Risposta_InterrogazioneLiquidazioniAperte_Types"/>
 *         &lt;element name="Risposta_InterrogazioneImpegniPerenti" type="{}Risposta_InterrogazioneImpegniPerenti_Types"/>
 *         &lt;element name="Risposta_PrenotazionePreimpegni" type="{}Risposta_PrenotazionePreimpegni_Types"/>
 *         &lt;element name="Risposta_CreateDelDocumento" type="{}Risposta_CreateDelDocumento_Types"/>
 *         &lt;element name="Risposta_DisponibilitaImpegno" type="{}Risposta_DisponibilitaImpegno_Types"/>
 *         &lt;element name="Risposta_InterrogaTipologiaReddito" type="{}Risposta_InterrogaTipologiaReddito_Types"/>
 *         &lt;element name="Risposta_InterrogaCodiceSiope" type="{}Risposta_InterrogaCodiceSiope_Types"/>
 *         &lt;element name="Risposta_InterrogaCapitoloEntrata" type="{}Risposta_InterrogaCapitoloEntrata_Types"/>
 *         &lt;element name="Risposta_InterrogaReversaliCollegabili" type="{}Risposta_InterrogaReversaliCollegabili_Types"/>
 *         &lt;element name="Risposta_InterrogaBeneficiariLiq" type="{}Risposta_InterrogaBeneficiariLiq_Types"/>
 *         &lt;element name="Risposta_InterrogaMandatiBeneficiariAtto" type="{}Risposta_InterrogaMandatiBeneficiariAtto_Types"/>
 *         &lt;element name="Risposta_InterrogazionePCF" type="{}Risposta_InterrogazionePCF_Types"/>
 *         &lt;element name="Risposta_InterrogazioneMandatiTrasparenza" type="{}Risposta_InterrogazioneMandatiTrasparenza_Types"/>
 *         &lt;element name="Risposta_InterrogazioneContratti" type="{}Risposta_InterrogazioneContratti_Types"/>
 *         &lt;element name="Risposta_InterrogazioneListaContratti" type="{}Risposta_InterrogazioneContratti_Types"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface SuccessoTypes {


    /**
     * Gets the value of the rispostaInterrogaCapitoloEntrata property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogaCapitoloEntrataTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaInterrogaCapitoloEntrataTypes getRispostaInterrogaCapitoloEntrata();

    /**
     * Sets the value of the rispostaInterrogaCapitoloEntrata property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogaCapitoloEntrataTypes}
     */
    void setRispostaInterrogaCapitoloEntrata(it.latraccia.entity.sic.risposta.RispostaInterrogaCapitoloEntrataTypes value);

    /**
     * Gets the value of the rispostaInterrogazioneListaContratti property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneContrattiTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaInterrogazioneContrattiTypes getRispostaInterrogazioneListaContratti();

    /**
     * Sets the value of the rispostaInterrogazioneListaContratti property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneContrattiTypes}
     */
    void setRispostaInterrogazioneListaContratti(it.latraccia.entity.sic.risposta.RispostaInterrogazioneContrattiTypes value);

    /**
     * Gets the value of the rispostaInterrogaTipologiaReddito property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogaTipologiaRedditoTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaInterrogaTipologiaRedditoTypes getRispostaInterrogaTipologiaReddito();

    /**
     * Sets the value of the rispostaInterrogaTipologiaReddito property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogaTipologiaRedditoTypes}
     */
    void setRispostaInterrogaTipologiaReddito(it.latraccia.entity.sic.risposta.RispostaInterrogaTipologiaRedditoTypes value);

    /**
     * Gets the value of the rispostaInterrogazionePCF property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazionePCFTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaInterrogazionePCFTypes getRispostaInterrogazionePCF();

    /**
     * Sets the value of the rispostaInterrogazionePCF property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazionePCFTypes}
     */
    void setRispostaInterrogazionePCF(it.latraccia.entity.sic.risposta.RispostaInterrogazionePCFTypes value);

    /**
     * Gets the value of the rispostaInterrogazioneObiettiviGestionali property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneObiettiviGestionaliTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaInterrogazioneObiettiviGestionaliTypes getRispostaInterrogazioneObiettiviGestionali();

    /**
     * Sets the value of the rispostaInterrogazioneObiettiviGestionali property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneObiettiviGestionaliTypes}
     */
    void setRispostaInterrogazioneObiettiviGestionali(it.latraccia.entity.sic.risposta.RispostaInterrogazioneObiettiviGestionaliTypes value);

    /**
     * Gets the value of the rispostaInterrogazioneBilancio property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneBilancioTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaInterrogazioneBilancioTypes getRispostaInterrogazioneBilancio();

    /**
     * Sets the value of the rispostaInterrogazioneBilancio property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneBilancioTypes}
     */
    void setRispostaInterrogazioneBilancio(it.latraccia.entity.sic.risposta.RispostaInterrogazioneBilancioTypes value);

    /**
     * Gets the value of the rispostaInterrogaMandatiBeneficiariAtto property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogaMandatiBeneficiariAttoTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaInterrogaMandatiBeneficiariAttoTypes getRispostaInterrogaMandatiBeneficiariAtto();

    /**
     * Sets the value of the rispostaInterrogaMandatiBeneficiariAtto property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogaMandatiBeneficiariAttoTypes}
     */
    void setRispostaInterrogaMandatiBeneficiariAtto(it.latraccia.entity.sic.risposta.RispostaInterrogaMandatiBeneficiariAttoTypes value);

    /**
     * Gets the value of the rispostaInterrogazionePreimpegniAperti property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazionePreimpegniApertiTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaInterrogazionePreimpegniApertiTypes getRispostaInterrogazionePreimpegniAperti();

    /**
     * Sets the value of the rispostaInterrogazionePreimpegniAperti property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazionePreimpegniApertiTypes}
     */
    void setRispostaInterrogazionePreimpegniAperti(it.latraccia.entity.sic.risposta.RispostaInterrogazionePreimpegniApertiTypes value);

    /**
     * Gets the value of the rispostaDisponibilitaPreImpegno property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaDisponibilitaPreImpegnoTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaDisponibilitaPreImpegnoTypes getRispostaDisponibilitaPreImpegno();

    /**
     * Sets the value of the rispostaDisponibilitaPreImpegno property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaDisponibilitaPreImpegnoTypes}
     */
    void setRispostaDisponibilitaPreImpegno(it.latraccia.entity.sic.risposta.RispostaDisponibilitaPreImpegnoTypes value);

    /**
     * Gets the value of the rispostaInterrogazioneImpegniAperti property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneImpegniApertiTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaInterrogazioneImpegniApertiTypes getRispostaInterrogazioneImpegniAperti();

    /**
     * Sets the value of the rispostaInterrogazioneImpegniAperti property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneImpegniApertiTypes}
     */
    void setRispostaInterrogazioneImpegniAperti(it.latraccia.entity.sic.risposta.RispostaInterrogazioneImpegniApertiTypes value);

    /**
     * Gets the value of the rispostaInterrogazioneCapitoliLiquidazioni property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneCapitoliTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaInterrogazioneCapitoliTypes getRispostaInterrogazioneCapitoliLiquidazioni();

    /**
     * Sets the value of the rispostaInterrogazioneCapitoliLiquidazioni property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneCapitoliTypes}
     */
    void setRispostaInterrogazioneCapitoliLiquidazioni(it.latraccia.entity.sic.risposta.RispostaInterrogazioneCapitoliTypes value);

    /**
     * Gets the value of the rispostaInterrogaCodiceSiope property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogaCodiceSiopeTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaInterrogaCodiceSiopeTypes getRispostaInterrogaCodiceSiope();

    /**
     * Sets the value of the rispostaInterrogaCodiceSiope property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogaCodiceSiopeTypes}
     */
    void setRispostaInterrogaCodiceSiope(it.latraccia.entity.sic.risposta.RispostaInterrogaCodiceSiopeTypes value);

    /**
     * Gets the value of the rispostaInterrogazioneMandatiTrasparenza property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneMandatiTrasparenzaTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaInterrogazioneMandatiTrasparenzaTypes getRispostaInterrogazioneMandatiTrasparenza();

    /**
     * Sets the value of the rispostaInterrogazioneMandatiTrasparenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneMandatiTrasparenzaTypes}
     */
    void setRispostaInterrogazioneMandatiTrasparenza(it.latraccia.entity.sic.risposta.RispostaInterrogazioneMandatiTrasparenzaTypes value);

    /**
     * Gets the value of the rispostaCreateDelDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaCreateDelDocumentoTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaCreateDelDocumentoTypes getRispostaCreateDelDocumento();

    /**
     * Sets the value of the rispostaCreateDelDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaCreateDelDocumentoTypes}
     */
    void setRispostaCreateDelDocumento(it.latraccia.entity.sic.risposta.RispostaCreateDelDocumentoTypes value);

    /**
     * Gets the value of the rispostaInterrogazioneCapitoli property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneCapitoliTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaInterrogazioneCapitoliTypes getRispostaInterrogazioneCapitoli();

    /**
     * Sets the value of the rispostaInterrogazioneCapitoli property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneCapitoliTypes}
     */
    void setRispostaInterrogazioneCapitoli(it.latraccia.entity.sic.risposta.RispostaInterrogazioneCapitoliTypes value);

    /**
     * Gets the value of the rispostaInterrogazioneLiquidazioniAperte property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneLiquidazioniAperteTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaInterrogazioneLiquidazioniAperteTypes getRispostaInterrogazioneLiquidazioniAperte();

    /**
     * Sets the value of the rispostaInterrogazioneLiquidazioniAperte property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneLiquidazioniAperteTypes}
     */
    void setRispostaInterrogazioneLiquidazioniAperte(it.latraccia.entity.sic.risposta.RispostaInterrogazioneLiquidazioniAperteTypes value);

    /**
     * Gets the value of the rispostaInterrogazioneImpegniPerenti property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneImpegniPerentiTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaInterrogazioneImpegniPerentiTypes getRispostaInterrogazioneImpegniPerenti();

    /**
     * Sets the value of the rispostaInterrogazioneImpegniPerenti property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneImpegniPerentiTypes}
     */
    void setRispostaInterrogazioneImpegniPerenti(it.latraccia.entity.sic.risposta.RispostaInterrogazioneImpegniPerentiTypes value);

    /**
     * Gets the value of the rispostaPrenotazionePreimpegni property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaPrenotazionePreimpegniTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaPrenotazionePreimpegniTypes getRispostaPrenotazionePreimpegni();

    /**
     * Sets the value of the rispostaPrenotazionePreimpegni property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaPrenotazionePreimpegniTypes}
     */
    void setRispostaPrenotazionePreimpegni(it.latraccia.entity.sic.risposta.RispostaPrenotazionePreimpegniTypes value);

    /**
     * Gets the value of the rispostaInterrogaReversaliCollegabili property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogaReversaliCollegabiliTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaInterrogaReversaliCollegabiliTypes getRispostaInterrogaReversaliCollegabili();

    /**
     * Sets the value of the rispostaInterrogaReversaliCollegabili property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogaReversaliCollegabiliTypes}
     */
    void setRispostaInterrogaReversaliCollegabili(it.latraccia.entity.sic.risposta.RispostaInterrogaReversaliCollegabiliTypes value);

    /**
     * Gets the value of the rispostaInterrogazioneContratti property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneContrattiTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaInterrogazioneContrattiTypes getRispostaInterrogazioneContratti();

    /**
     * Sets the value of the rispostaInterrogazioneContratti property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogazioneContrattiTypes}
     */
    void setRispostaInterrogazioneContratti(it.latraccia.entity.sic.risposta.RispostaInterrogazioneContrattiTypes value);

    /**
     * Gets the value of the rispostaDisponibilitaImpegno property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaDisponibilitaImpegnoTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaDisponibilitaImpegnoTypes getRispostaDisponibilitaImpegno();

    /**
     * Sets the value of the rispostaDisponibilitaImpegno property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaDisponibilitaImpegnoTypes}
     */
    void setRispostaDisponibilitaImpegno(it.latraccia.entity.sic.risposta.RispostaDisponibilitaImpegnoTypes value);

    /**
     * Gets the value of the rispostaInterrogaBeneficiariLiq property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogaBeneficiariLiqTypes}
     */
    it.latraccia.entity.sic.risposta.RispostaInterrogaBeneficiariLiqTypes getRispostaInterrogaBeneficiariLiq();

    /**
     * Sets the value of the rispostaInterrogaBeneficiariLiq property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.sic.risposta.RispostaInterrogaBeneficiariLiqTypes}
     */
    void setRispostaInterrogaBeneficiariLiq(it.latraccia.entity.sic.risposta.RispostaInterrogaBeneficiariLiqTypes value);

}
