//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.27 at 04:58:22 PM CET 
//


package it.latraccia.entity.anasic.risposta;


/**
 * Java content class for Messaggio_RispostaMassiva element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/simonebrunox/Desktop/JAXB/XSD/Anagraf/RispostaAnaSIC.xsd line 6)
 * <p>
 * <pre>
 * &lt;element name="Messaggio_RispostaMassiva" type="{}MessaggioRispostaMassiva_Types"/>
 * </pre>
 * 
 */
public interface MessaggioRispostaMassiva
    extends javax.xml.bind.Element, it.latraccia.entity.anasic.risposta.MessaggioRispostaMassivaTypes
{


}
