//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.02 at 12:37:18 PM CET 
//


package it.latraccia.entity.anasic.risposta;


/**
 * Java content class for Sede_Types complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/simonebrunox/Desktop/SIC/XSD/Anagraf/RispostaAnaSIC.xsd line 376)
 * <p>
 * <pre>
 * &lt;complexType name="Sede_Types">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdSede">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-9]{10}"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="Indirizzo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IdComune">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-9]{10}"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="Comune" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CAP">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="10"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="Telefono" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EMail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Bollo">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="S"/>
 *             &lt;enumeration value="N"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="DataCreazione" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="NomeSede">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="15"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="IdTipoPagamento">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-9]{10}"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="DescTipoPagamento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ListaDatiBancari" type="{}ListaContiBancari_Types"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface SedeTypes {


    /**
     * Lista dei Dati Bancari
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.anasic.risposta.ListaContiBancariTypes}
     */
    it.latraccia.entity.anasic.risposta.ListaContiBancariTypes getListaDatiBancari();

    /**
     * Lista dei Dati Bancari
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.anasic.risposta.ListaContiBancariTypes}
     */
    void setListaDatiBancari(it.latraccia.entity.anasic.risposta.ListaContiBancariTypes value);

    /**
     * Data di Creazione
     * 
     * @return
     *     possible object is
     *     {@link null}
     *     {@link java.util.Calendar}
     */
    java.util.Calendar getDataCreazione();

    /**
     * Data di Creazione
     * 
     * @param value
     *     allowed object is
     *     {@link null}
     *     {@link java.util.Calendar}
     */
    void setDataCreazione(java.util.Calendar value);

    /**
     * Nome della sede
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     *     {@link null}
     */
    java.lang.String getNomeSede();

    /**
     * Nome della sede
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     *     {@link null}
     */
    void setNomeSede(java.lang.String value);

    /**
     * EMail della sede
     * 
     * @return
     *     possible object is
     *     {@link null}
     *     {@link java.lang.String}
     */
    java.lang.String getEMail();

    /**
     * EMail della sede
     * 
     * @param value
     *     allowed object is
     *     {@link null}
     *     {@link java.lang.String}
     */
    void setEMail(java.lang.String value);

    /**
     * Identificativo Comune della sede
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     *     {@link null}
     */
    java.lang.String getIdComune();

    /**
     * Identificativo Comune della sede
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     *     {@link null}
     */
    void setIdComune(java.lang.String value);

    /**
     * Comune della sede
     * 
     * @return
     *     possible object is
     *     {@link null}
     *     {@link java.lang.String}
     */
    java.lang.String getComune();

    /**
     * Comune della sede
     * 
     * @param value
     *     allowed object is
     *     {@link null}
     *     {@link java.lang.String}
     */
    void setComune(java.lang.String value);

    /**
     * Descrizione della Tipologia del pagamento
     * 
     * @return
     *     possible object is
     *     {@link null}
     *     {@link java.lang.String}
     */
    java.lang.String getDescTipoPagamento();

    /**
     * Descrizione della Tipologia del pagamento
     * 
     * @param value
     *     allowed object is
     *     {@link null}
     *     {@link java.lang.String}
     */
    void setDescTipoPagamento(java.lang.String value);

    /**
     * CAP della sede
     * 
     * @return
     *     possible object is
     *     {@link null}
     *     {@link java.lang.String}
     */
    java.lang.String getCAP();

    /**
     * CAP della sede
     * 
     * @param value
     *     allowed object is
     *     {@link null}
     *     {@link java.lang.String}
     */
    void setCAP(java.lang.String value);

    /**
     * Identificativo Sede SIC
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIdSede();

    /**
     * Identificativo Sede SIC
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIdSede(java.lang.String value);

    /**
     * Bollo (= S o N)
     * 
     * @return
     *     possible object is
     *     {@link null}
     *     {@link java.lang.String}
     */
    java.lang.String getBollo();

    /**
     * Bollo (= S o N)
     * 
     * @param value
     *     allowed object is
     *     {@link null}
     *     {@link java.lang.String}
     */
    void setBollo(java.lang.String value);

    /**
     * Indirizzo della sede
     * 
     * @return
     *     possible object is
     *     {@link null}
     *     {@link java.lang.String}
     */
    java.lang.String getIndirizzo();

    /**
     * Indirizzo della sede
     * 
     * @param value
     *     allowed object is
     *     {@link null}
     *     {@link java.lang.String}
     */
    void setIndirizzo(java.lang.String value);

    /**
     * Telefono della sede
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     *     {@link null}
     */
    java.lang.String getTelefono();

    /**
     * Telefono della sede
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     *     {@link null}
     */
    void setTelefono(java.lang.String value);

    /**
     * Identificativo Tipo Pagamento SIC
     * 
     * @return
     *     possible object is
     *     {@link null}
     *     {@link java.lang.String}
     */
    java.lang.String getIdTipoPagamento();

    /**
     * Identificativo Tipo Pagamento SIC
     * 
     * @param value
     *     allowed object is
     *     {@link null}
     *     {@link java.lang.String}
     */
    void setIdTipoPagamento(java.lang.String value);

    /**
     * Telefono della sede
     * 
     * @return
     *     possible object is
     *     {@link null}
     *     {@link java.lang.String}
     */
    java.lang.String getFax();

    /**
     * Telefono della sede
     * 
     * @param value
     *     allowed object is
     *     {@link null}
     *     {@link java.lang.String}
     */
    void setFax(java.lang.String value);

}
