//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.02 at 12:37:18 PM CET 
//


package it.latraccia.entity.anasic.risposta;


/**
 * Java content class for Successo_Types complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/simonebrunox/Desktop/SIC/XSD/Anagraf/RispostaAnaSIC.xsd line 94)
 * <p>
 * <pre>
 * &lt;complexType name="Successo_Types">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Risposta_InterrogaAnagrafica" type="{}Risposta_InterrogaAnagrafica_Types"/>
 *         &lt;element name="Risposta_InterrogaAnagraficaContratti" type="{}Risposta_InterrogaAnagraficaContratti_Types"/>
 *         &lt;element name="Risposta_VerificaAnagrafica" type="{}Risposta_VerificaAnagrafica_Types"/>
 *         &lt;element name="Risposta_CreaAnagrafica" type="{}Risposta_CreaAnagrafica_Types"/>
 *         &lt;element name="Risposta_CreaSede" type="{}Risposta_CreaSede_Types"/>
 *         &lt;element name="Risposta_CreaContoBancario" type="{}Risposta_CreaContoBancario_Types"/>
 *         &lt;element name="Risposta_InterrogaComuni" type="{}Risposta_InterrogaComuni_Types"/>
 *         &lt;element name="Risposta_ModificaAnagrafica" type="{}Risposta_ModificaAnagrafica_Types"/>
 *         &lt;element name="Risposta_ModificaSede" type="{}Risposta_ModificaSede_Types"/>
 *         &lt;element name="Risposta_ModificaContoBancario" type="{}Risposta_ModificaContoBancario_Types"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface SuccessoTypes {


    /**
     * Gets the value of the rispostaInterrogaComuni property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaInterrogaComuniTypes}
     */
    it.latraccia.entity.anasic.risposta.RispostaInterrogaComuniTypes getRispostaInterrogaComuni();

    /**
     * Sets the value of the rispostaInterrogaComuni property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaInterrogaComuniTypes}
     */
    void setRispostaInterrogaComuni(it.latraccia.entity.anasic.risposta.RispostaInterrogaComuniTypes value);

    /**
     * Gets the value of the rispostaModificaAnagrafica property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaModificaAnagraficaTypes}
     */
    it.latraccia.entity.anasic.risposta.RispostaModificaAnagraficaTypes getRispostaModificaAnagrafica();

    /**
     * Sets the value of the rispostaModificaAnagrafica property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaModificaAnagraficaTypes}
     */
    void setRispostaModificaAnagrafica(it.latraccia.entity.anasic.risposta.RispostaModificaAnagraficaTypes value);

    /**
     * Gets the value of the rispostaCreaSede property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaCreaSedeTypes}
     */
    it.latraccia.entity.anasic.risposta.RispostaCreaSedeTypes getRispostaCreaSede();

    /**
     * Sets the value of the rispostaCreaSede property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaCreaSedeTypes}
     */
    void setRispostaCreaSede(it.latraccia.entity.anasic.risposta.RispostaCreaSedeTypes value);

    /**
     * Gets the value of the rispostaVerificaAnagrafica property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaVerificaAnagraficaTypes}
     */
    it.latraccia.entity.anasic.risposta.RispostaVerificaAnagraficaTypes getRispostaVerificaAnagrafica();

    /**
     * Sets the value of the rispostaVerificaAnagrafica property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaVerificaAnagraficaTypes}
     */
    void setRispostaVerificaAnagrafica(it.latraccia.entity.anasic.risposta.RispostaVerificaAnagraficaTypes value);

    /**
     * Gets the value of the rispostaModificaSede property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaModificaSedeTypes}
     */
    it.latraccia.entity.anasic.risposta.RispostaModificaSedeTypes getRispostaModificaSede();

    /**
     * Sets the value of the rispostaModificaSede property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaModificaSedeTypes}
     */
    void setRispostaModificaSede(it.latraccia.entity.anasic.risposta.RispostaModificaSedeTypes value);

    /**
     * Gets the value of the rispostaModificaContoBancario property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaModificaContoBancarioTypes}
     */
    it.latraccia.entity.anasic.risposta.RispostaModificaContoBancarioTypes getRispostaModificaContoBancario();

    /**
     * Sets the value of the rispostaModificaContoBancario property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaModificaContoBancarioTypes}
     */
    void setRispostaModificaContoBancario(it.latraccia.entity.anasic.risposta.RispostaModificaContoBancarioTypes value);

    /**
     * Gets the value of the rispostaInterrogaAnagrafica property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaInterrogaAnagraficaTypes}
     */
    it.latraccia.entity.anasic.risposta.RispostaInterrogaAnagraficaTypes getRispostaInterrogaAnagrafica();

    /**
     * Sets the value of the rispostaInterrogaAnagrafica property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaInterrogaAnagraficaTypes}
     */
    void setRispostaInterrogaAnagrafica(it.latraccia.entity.anasic.risposta.RispostaInterrogaAnagraficaTypes value);

    /**
     * Gets the value of the rispostaInterrogaAnagraficaContratti property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaInterrogaAnagraficaContrattiTypes}
     */
    it.latraccia.entity.anasic.risposta.RispostaInterrogaAnagraficaContrattiTypes getRispostaInterrogaAnagraficaContratti();

    /**
     * Sets the value of the rispostaInterrogaAnagraficaContratti property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaInterrogaAnagraficaContrattiTypes}
     */
    void setRispostaInterrogaAnagraficaContratti(it.latraccia.entity.anasic.risposta.RispostaInterrogaAnagraficaContrattiTypes value);

    /**
     * Gets the value of the rispostaCreaAnagrafica property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaCreaAnagraficaTypes}
     */
    it.latraccia.entity.anasic.risposta.RispostaCreaAnagraficaTypes getRispostaCreaAnagrafica();

    /**
     * Sets the value of the rispostaCreaAnagrafica property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaCreaAnagraficaTypes}
     */
    void setRispostaCreaAnagrafica(it.latraccia.entity.anasic.risposta.RispostaCreaAnagraficaTypes value);

    /**
     * Gets the value of the rispostaCreaContoBancario property.
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaCreaContoBancarioTypes}
     */
    it.latraccia.entity.anasic.risposta.RispostaCreaContoBancarioTypes getRispostaCreaContoBancario();

    /**
     * Sets the value of the rispostaCreaContoBancario property.
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.anasic.risposta.RispostaCreaContoBancarioTypes}
     */
    void setRispostaCreaContoBancario(it.latraccia.entity.anasic.risposta.RispostaCreaContoBancarioTypes value);

}
