//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.02 at 12:37:18 PM CET 
//


package it.latraccia.entity.anasic.risposta;


/**
 * Java content class for MessaggioRispostaMassiva_Types complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/simonebrunox/Desktop/SIC/XSD/Anagraf/RispostaAnaSIC.xsd line 33)
 * <p>
 * <pre>
 * &lt;complexType name="MessaggioRispostaMassiva_Types">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RispostaMassiva_Type" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IdAnagraficaMittente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;choice>
 *                     &lt;element name="Risposta_ProcessaAnagrafica" type="{}Risposta_ProcessaAnagrafica_Types"/>
 *                     &lt;element name="Eccezione" type="{}Eccezione_Types"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface MessaggioRispostaMassivaTypes {


    /**
     * Gets the value of the RispostaMassivaType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the RispostaMassivaType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRispostaMassivaType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link it.latraccia.entity.anasic.risposta.MessaggioRispostaMassivaTypes.RispostaMassivaTypeType}
     * 
     */
    java.util.List getRispostaMassivaType();


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/simonebrunox/Desktop/SIC/XSD/Anagraf/RispostaAnaSIC.xsd line 36)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IdAnagraficaMittente" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;choice>
     *           &lt;element name="Risposta_ProcessaAnagrafica" type="{}Risposta_ProcessaAnagrafica_Types"/>
     *           &lt;element name="Eccezione" type="{}Eccezione_Types"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface RispostaMassivaTypeType {


        /**
         * Gets the value of the rispostaProcessaAnagrafica property.
         * 
         * @return
         *     possible object is
         *     {@link it.latraccia.entity.anasic.risposta.RispostaProcessaAnagraficaTypes}
         */
        it.latraccia.entity.anasic.risposta.RispostaProcessaAnagraficaTypes getRispostaProcessaAnagrafica();

        /**
         * Sets the value of the rispostaProcessaAnagrafica property.
         * 
         * @param value
         *     allowed object is
         *     {@link it.latraccia.entity.anasic.risposta.RispostaProcessaAnagraficaTypes}
         */
        void setRispostaProcessaAnagrafica(it.latraccia.entity.anasic.risposta.RispostaProcessaAnagraficaTypes value);

        /**
         * Rappresenta un generico messaggio di errore
         * 
         * @return
         *     possible object is
         *     {@link it.latraccia.entity.anasic.risposta.EccezioneTypes}
         */
        it.latraccia.entity.anasic.risposta.EccezioneTypes getEccezione();

        /**
         * Rappresenta un generico messaggio di errore
         * 
         * @param value
         *     allowed object is
         *     {@link it.latraccia.entity.anasic.risposta.EccezioneTypes}
         */
        void setEccezione(it.latraccia.entity.anasic.risposta.EccezioneTypes value);

        /**
         * Identificativo utilizzato dal mittente per individuare l'anagrafica inviata
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getIdAnagraficaMittente();

        /**
         * Identificativo utilizzato dal mittente per individuare l'anagrafica inviata
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setIdAnagraficaMittente(java.lang.String value);

    }

}
