//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.02 at 12:37:18 PM CET 
//


package it.latraccia.entity.anasic.risposta;


/**
 * Java content class for Messaggio_Risposta element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/simonebrunox/Desktop/SIC/XSD/Anagraf/RispostaAnaSIC.xsd line 3)
 * <p>
 * <pre>
 * &lt;element name="Messaggio_Risposta" type="{}MessaggioRisposta_Types"/>
 * </pre>
 * 
 */
public interface MessaggioRisposta
    extends javax.xml.bind.Element, it.latraccia.entity.anasic.risposta.MessaggioRispostaTypes
{


}
