//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.28 at 01:25:27 PM CET 
//


package it.latraccia.entity.anasic.richiesta;


/**
 * Java content class for MessaggioRichiesta_Types complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/Users/simonebrunox/Desktop/JAXB/XSD/Anagraf/RichiestaAnaSIC.xsd line 4)
 * <p>
 * <pre>
 * &lt;complexType name="MessaggioRichiesta_Types">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Intestazione" type="{}Intestazione_Types"/>
 *         &lt;sequence>
 *           &lt;element name="Richiesta" type="{}Richiesta_Types"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface MessaggioRichiestaTypes {


    /**
     * Header contenente informazioni su mittente, destinatario e tipo di richiesta
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.anasic.richiesta.IntestazioneTypes}
     */
    it.latraccia.entity.anasic.richiesta.IntestazioneTypes getIntestazione();

    /**
     * Header contenente informazioni su mittente, destinatario e tipo di richiesta
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.anasic.richiesta.IntestazioneTypes}
     */
    void setIntestazione(it.latraccia.entity.anasic.richiesta.IntestazioneTypes value);

    /**
     * Contiene tutti i tipi di richiesta
     * 
     * @return
     *     possible object is
     *     {@link it.latraccia.entity.anasic.richiesta.RichiestaTypes}
     */
    it.latraccia.entity.anasic.richiesta.RichiestaTypes getRichiesta();

    /**
     * Contiene tutti i tipi di richiesta
     * 
     * @param value
     *     allowed object is
     *     {@link it.latraccia.entity.anasic.richiesta.RichiestaTypes}
     */
    void setRichiesta(it.latraccia.entity.anasic.richiesta.RichiestaTypes value);

}
